### ISSUE TITLE
g:asyncrun_status with airline always shows success

### ISSUE THREAD

**Issue by deathmaz** [skywind3000/asyncrun.vim#10]
Hi @skywind3000 
I added `g:asyncrun_status` to airline to make it show the status of asyncrun
`let g:airline_section_error = airline#section#create_right(['%{g:asyncrun_status}'])`

But it always shows `success` even when the result of command execution is error
I recorded the issue with asciinema https://asciinema.org/a/a4ksqp8enp5tx29uyoczy7f7q

So first I run two commands with `:AsyncRun` that return errors
After that I run the same two commands in NeoVim terminal just to show the actual output.

I'm using `NVIM v0.1.6-175-g7246750`

Thank you!

**Comment by skywind3000** [comment]
I have trigger a `:redrawstatus!` after job finished, does this command has no effect on airline ?
how to trigger a airline redraw ??

**Comment by skywind3000** [comment]
Found some information:
you should call ':AirlineRefresh' twice:

[https://github.com/vim-airline/vim-airline/issues/539](https://github.com/vim-airline/vim-airline/issues/539)

you could add these line below to your .vimrc:

```VimL
function! RefreshUI()
  if exists(':AirlineRefresh')
    AirlineRefresh
    AirlineRefresh
  else
    " Clear & redraw the screen, then redraw all statuslines.
    redraw!
    redrawstatus!
  endif
endfunction

let g:asyncrun_exit = 'call RefreshUI()'
```

**Comment by deathmaz** [comment]
Thank's for quick response!
Tried `RefreshUI()` but the result is the same.
Are you sure that the problem is because airline didn't redraw?
 As you may see here https://asciinema.org/a/a4ksqp8enp5tx29uyoczy7f7q when i'm running
`:AsyncRun npm install non-existed-package` in to bottom right corner the status changes to `running` and then `success`

**Comment by skywind3000** [comment]
what is the value of `g:asyncrun_code` after finished ?

```VimL
:echo g:asyncrun_code
```

**Comment by deathmaz** [comment]
It returns `0`

**Comment by skywind3000** [comment]
I think I know what's wrong, you are using neovim.
and exit code in neovim has not been handled in the write way.

fixed.
please update

**Comment by deathmaz** [comment]
It works!
Thank you very much for your effort 👍

**Comment by skywind3000** [comment]
welcome, do my best to make it a better competitor to vim-dispatch now
could you please give me your airline config, 
I am going to write a wiki page to guide people how to config airline to display asyncrun status

**Comment by deathmaz** [comment]
Sure, this is the only line that i added to make the asyncrun status visible in airline
```viml
let g:airline_section_error = airline#section#create_right(['%{g:asyncrun_status}'])
```
In this way it will be shown in the error section of ariline
Also i should mention that airline has multiple sections and i guess the status could be placed in any of them

Here an excerpt from airline's help page:

```viml
  variable names                default contents
  ----------------------------------------------------------------------------
  let g:airline_section_a       (mode, crypt, paste, spell, iminsert)
  let g:airline_section_b       (hunks, branch)
  let g:airline_section_c       (bufferline or filename)
  let g:airline_section_gutter  (readonly, csv)
  let g:airline_section_x       (tagbar, filetype, virtualenv)
  let g:airline_section_y       (fileencoding, fileformat)
  let g:airline_section_z       (percentage, line number, column number)
  let g:airline_section_error   (ycm_error_count, syntastic, eclim)
  let g:airline_section_warning (ycm_warning_count, whitespace)

  " here is an example of how you could replace the branch indicator with
  " the current working directory, followed by the filename.
  let g:airline_section_b = '%{getcwd()}'
  let g:airline_section_c = '%t'
```
