### ISSUE TITLE
Output of go run % not displayed

### ISSUE THREAD

**Issue by jychri** [skywind3000/asyncrun.vim#102]
Hello,

Am I missing something obvious? Running `:AsyncRun! go run %` doesn't print the output of main.go. Is there a better way that I should be running basic tests with asyncrun?

Thank you,

jychri
![screen shot 2018-04-25 at 10 01 15 am](https://user-images.githubusercontent.com/5490881/39254689-52fb9d58-4870-11e8-9823-900e377f9f9a.png)
![screen shot 2018-04-25 at 10 02 19 am](https://user-images.githubusercontent.com/5490881/39254690-531209c6-4870-11e8-834e-ac7e50bc0082.png)
![screen shot 2018-04-25 at 10 04 25 am](https://user-images.githubusercontent.com/5490881/39254691-53244d02-4870-11e8-9476-e2bc188b4425.png)

**Comment by skywind3000** [comment]
Try this:

```VimL
:AsyncRun! -raw go run %
```

**Comment by jychri** [comment]
Interesting. `:AsyncRun! -raw go run %` doesn't display anything.
![screen shot 2018-04-25 at 10 32 36 am](https://user-images.githubusercontent.com/5490881/39256324-3b07399c-4874-11e8-8d13-2475a1fea118.png)
![screen shot 2018-04-25 at 10 32 46 am](https://user-images.githubusercontent.com/5490881/39256325-3b15f734-4874-11e8-9239-cbdc977a72c1.png)

**Comment by jychri** [comment]
And `AsyncRun! go run % -raw` displays the same output as `AsyncRun! go run %`

![screen shot 2018-04-25 at 10 35 32 am](https://user-images.githubusercontent.com/5490881/39256430-80e024d8-4874-11e8-9c27-50f2cb2567be.png)

**Comment by skywind3000** [comment]
the quickfix window wasn't open yet in the screen capture of ":AsyncRun! -raw go run %" 

and in the next image, quickfix window is opened. but a `-raw` is missing in your command.

**Comment by jychri** [comment]
`:AsyncRun! -raw go run %` isn't opening the quickfix window, it's very strange.

**Comment by jychri** [comment]
But `:AsyncRun! go run %` does.

**Comment by skywind3000** [comment]
you can manually open the quick fix window
By copen,then run 

AsyncRun -raw go run %

To see the output

**Comment by skywind3000** [comment]
vim-go will modify `errorformat` and will filter out your non-error messages, see here:

https://github.com/skywind3000/asyncrun.vim/wiki/FAQ#cant-capture-commands-output-in-quickfix-window-

So I want confirm that by using `:AsyncRun -raw` , could you please feed back the result and remember open the quickfix window before that by a `:copen 8` command.

If the quickfix window can't be opened by `AsyncRun` there may be an ui issue, but not about this.

**Comment by jychri** [comment]
Thank you so much for helping me through this issue.

`:copen 8` followed by `:AsyncRun -raw go run %` in the primary buffer displays the expected output.

![screen shot 2018-04-26 at 1 11 03 pm](https://user-images.githubusercontent.com/5490881/39323929-ac831408-4953-11e8-872d-b0064e6b202e.png)

**Comment by skywind3000** [comment]
OK, now we will check why the quickfix window cannot be opened by AsyncRun.

Have you have this option in your `vimrc` ?

```VimL
let g:asyncrun_open = 8
```

It will open the quickfix window after calling `:AsyncRun` command.

see here:
https://github.com/skywind3000/asyncrun.vim/wiki/Options#gasyncrun_open

**Comment by jychri** [comment]
That was not in my `vimrc`. I just added `let g:asyncrun_open = 8` and now it is working perfectly. Thank you so much, my apologies for overlooking this in the docs.
