### ISSUE TITLE
python运行matplotlib画图后，在Vim中AsyncStop会自动关闭图，但是NeoVim不会

### ISSUE THREAD

**Issue by Chandlercjy** [skywind3000/asyncrun.vim#105]
如题，用Matplotlib随便用asyncrun画个图，然后AsyncStop的话Vim8会自动将图关闭，但是Neovim不会。希望修复这个bug，或者提供设置进行选择是否自动将图关闭，感谢！！

**Comment by skywind3000** [comment]
啥意思？画图的代码是啥？命令是啥？操作系统？vim版本？截图？你这样什么信息都没有，让我无从诊断。

**Comment by Chandlercjy** [comment]
非常抱歉！是我没说清楚。

画图的代码：
```python
import matplotlib.pyplot as plt

x = [1, 2, 3]
y = [1, 2, 3]

plt.plot(x, y)
plt.show()
```
命令： :AsyncRun python %
操作系统：macOS 10.13.3
vim版本：NVIM v0.2.2 
运行之后效果：
![image](https://user-images.githubusercontent.com/22489018/39869251-debb83ce-542a-11e8-8482-c3097b78848d.png)

运行 :AsyncStop之后效果：
![image](https://user-images.githubusercontent.com/22489018/39869298-fbf7849c-542a-11e8-9de3-4a04d8bb254a.png)

我期望的效果：
希望左边的画图窗口能自动关闭。就像直接在命令行运行这个画图脚本后，若按ctrl-c中断脚本，画图窗口会自动关闭。

补充说明：
1. 上个版本(好像是上个，还是前个，有点忘了）的asyncrun运行的时候，是能实现窗口自动关闭的。但是最近更新了插件成最新版本，同时也更新的vim版本，就出现这种状况。所以我也不太清楚是asyncrun的问题还是vim本身的问题。
2. 好像vim8.0也会出现上述情况，这一点不太确定，因为目前主要用Neovim了。

非常感谢！如有需要提供其他信息请再提出。

**Comment by Chandlercjy** [comment]
更新最近版本asyncrun和neovim之后，问题消失了：）
