### ISSUE TITLE
[windows gui]quickfix无法显示输出

### ISSUE THREAD

**Issue by wining** [skywind3000/asyncrun.vim#107]
执行命令“AsyncRun go run  %”，发现所有的 printf 都不显示在quickfix里  
经检查发现是由ftplugin/go.vim  “compiler go”导致的 （注释掉是好的）  
vim版本：8.1 （1-26）  只有windows gui版本有问题
请问这是什么原因造成的？

**Comment by skywind3000** [comment]
试试这个：

```VimL
:AsyncRun -raw go run %
```

**Comment by wining** [comment]
好了！ 感谢

**Comment by skywind3000** [comment]
原因是 errorformat 被修改了，会把无法匹配到的额外内容全部过滤掉，你可以改回来，或者加 `-raw`

我推荐你看下 wiki：

https://github.com/skywind3000/asyncrun.vim/wiki/Better-way-for-C-and-Cpp-development-in-Vim-8

**Comment by wining** [comment]
ok，不好意思了，wiki已经有了，没仔细看
