### ISSUE TITLE
E118 and cxpr [] by default

### ISSUE THREAD

**Issue by skgbanga** [skywind3000/asyncrun.vim#11]
Hello,
First of all, great plugin!

Two quick question:
1. When I run a command via AsyncRun, I get this error:
> E118: Too many arguments for function: setqflist

Everything works correctly though. So I am not sure why I get this error.

2. Would it be possible to clear out the quick fix list by default the next time I run an AsyncRun command? Right now, I have to do this manually via typing:

> :cexpr []

If this can happen, everytime I run a command, that would be convenient.

**Comment by skywind3000** [comment]
I used a new version of `setqflist` , which has one more parameter in the latest vim and does not compatible with old vim.
And then I released a new asyncrun which will check the vim version, and use only two parameters in elder vim .

you may try the latest asyncrun, it is supposed to clear the quickfix window, if there is no error.

**Comment by skywind3000** [comment]
one more thing , what version of vim are you using ?

**Comment by skgbanga** [comment]
@skywind3000 you were absolutely right. I changed my terminal window, and that window didn't have my latest zshrc sourced, and hence I was using 7.4 only! Apologies for the wrong info!

Closing the ticket.
