### ISSUE TITLE
Windows vim运行时出问题

### ISSUE THREAD

**Issue by GooCoder** [skywind3000/asyncrun.vim#113]
运行的时候出了这个错误，完全看不懂。
![f w yb2jknt ttfa_0qg7](https://user-images.githubusercontent.com/39628662/41610654-5d1cb4e4-7420-11e8-9194-9f0edefe95b3.png)
这是我的vimrc
![image](https://user-images.githubusercontent.com/39628662/41610679-699f5d0c-7420-11e8-8163-4ee70d9d8b3b.png)

**Comment by skywind3000** [comment]
ale出错啊，你没见么，是不是ale哪里没有配置对？升级下试试。另外，建议写成：

```VimL
let $PYTHONUNBUFFERED=1 
exec 'AsyncRun! -raw -cwd=<root> python "$(FILE_PATH)"'
```

这样体验更好：
1. 会到文件目录下运行该文件
2. 避免文件名包含空格
3. 输出不匹配 errorformat
4. 关闭 python 缓存（后台执行时python会进入输出缓存模式）

参考：
https://github.com/skywind3000/asyncrun.vim/wiki/Better-way-for-C-and-Cpp-development-in-Vim-8

**Comment by GooCoder** [comment]
谢谢您的回答。我认为在我的环境上ale和asyncrun是冲突的。
1. 禁用ale，运行asyncrun，一切ok。
![image](https://user-images.githubusercontent.com/39628662/41643886-20d83d12-749f-11e8-8f36-06ebe152f27a.png)
2. 禁用asyncrun，运行ale，一切ok。从图中可以看到ale正常工作了，而且用的是我安装的flake8语法检错工具。
![image](https://user-images.githubusercontent.com/39628662/41644014-7d35013a-749f-11e8-8393-90a9f8b6d221.png)
3. 两者都运行，出错。
![image](https://user-images.githubusercontent.com/39628662/41644232-08b39ff0-74a0-11e8-8f38-ff96b3d70b5e.png)

我对ale没有做什么特殊的配置。只有以下几步。
1. vimrc中添加`Plug 'w0rp/ale'`
2. `:PlugInstall`
3. cmd中运行`pip install flake8`

ale配置文件如下
```
" 保存文件时自动检查语法错误
let g:ale_fix_on_save = 1

" 语法错误提示信息的输出格式
let g:ale_echo_msg_format = '[%linter%]-[%severity%]-%s'
```
安装asyncrun也和常规相同。
1. vimrc中添加`Plug 'skywind3000/asyncrun.vim'`
2. `:PlugInstall`

asyncrun的配置如下
```
" 关闭Python缓存
let $PYTHONUNBUFFERED=1

" 每次运行AsyncRunStart的时候自动打开quickfix窗口
augroup MyGroup
    autocmd User AsyncRunStart call asyncrun#quickfix_toggle(8, 1)
augroup END

" F9 打开/关闭quickfix窗口
noremap <F9> :call asyncrun#quickfix_toggle(8)<cr>
```
一切都很中规中矩。我也试图更新了ale和asyncrun，但是并没有什么效果。
您可以帮帮我吗？谢谢了！

**Comment by skywind3000** [comment]
我没碰到过，你 vim 什么版本啊？是最新 8.1 么？

**Comment by GooCoder** [comment]
vim官方编译的8.1.1，最新的ale和asyncrun。

**Comment by skywind3000** [comment]
你试试，是不是用 caddexpr 命令ale都会出错？打开 quickfix 以后：

:caddexpr “hello world”

看看有无问题？

**Comment by GooCoder** [comment]
是可以的，没有任何报错。我觉得我的ale配置没有问题，毕竟可以提示错误。难道是我应该换一个语法检错工具吗，不用flake8？

**Comment by GooCoder** [comment]
真的是好奇怪啊，我分别执行`:w`和`:AsyncRun! python %`没有问题，但是用F5执行就有问题。
![image](https://user-images.githubusercontent.com/39628662/41667896-a7ac754c-74e0-11e8-9fc3-fe9ba560bb73.png)

**Comment by skywind3000** [comment]
把fix on save 去掉

**Comment by GooCoder** [comment]
还是不行，哭了，为什么手动用指令执行没问题，用快捷键就会出问题。。。

**Comment by GooCoder** [comment]
现在总结起来是这种情况：
1. 打开文件什么都不干，第一件事就是手动执行`:w`和`:AsyncRun! python %`，一切都ok。但是一旦开始写代码，立马报错(我猜写代码的时候才激活了ale插件)。
2. 打开文件什么都不干，直接用F5快捷键，立马报错。
谢谢您的耐心回答！我认为这个问题不是出在asyncrun或者ale上，而是因为我没有配置好这两个插件。
我打算重新安装gvim，并再次安装插件。
再次向您表达谢意！

**Comment by skywind3000** [comment]
有可能是ale的bug，你可以试试关闭ale的自动fix功能，删除你F5函数里 exec “w” 那行看看
