### ISSUE TITLE
'Failed to create ConsoleBuf!' when buid with nmake

### ISSUE THREAD

**Issue by aj3423** [skywind3000/asyncrun.vim#119]
- Environment:  
  Windows10, GVim 8.1
- .vimrc configuration:
  Plug 'skywind3000/asyncrun.vim'
  let g:asyncrun_encs = 'gbk'

Both 'cd debug' and 'nmake' works, but  'cd debug & nmake' results in lots of error:
![2018-08-02_004917](https://user-images.githubusercontent.com/4710875/43536102-53c4eb38-95ee-11e8-8b0a-01a59b34e942.jpg)

**Comment by skywind3000** [comment]
nmake 有没有办法禁止色彩输出？？管道不支持色彩。一般应该检测下是否是终端还是管道，是管道就不设置色彩。

**Comment by aj3423** [comment]
我是用的cmake生成nmake工程，再用nmake编译。我试了cmake可以关掉颜色 `SET(CMAKE_COLOR_MAKEFILE OFF)`，在cmd下打nmake的确完全没颜色了，但再用 :AsyncRun 还是有一堆上图的输出，但区别是这次能把错误也显示进来了。

![1](https://user-images.githubusercontent.com/4710875/43758749-ab76afe6-9a4f-11e8-8240-fb2813a8aaca.png)

剩下的这些可能是啥情况。。

**Comment by skywind3000** [comment]
试试最新版里的一个选项：

```VimL
let g:asyncrun_stdin = has('win32') || has('win64')
```

AsyncRun 避免有的进程因为要从 stdin 读取数据而永远无法结束，因此启动进程时是关闭了 stdin 的，cmake 在 windows 下会检测 stdin 是否可用，否则会一直报错（unix下面没问题）。因此我加了一个选项来允许 stdin。
