### ISSUE TITLE
[Question] Run multiple commands

### ISSUE THREAD

**Issue by deathmaz** [skywind3000/asyncrun.vim#12]
Hi @skywind3000 
With vim-dispatch i can run multiple processes which will be started in separate tmux panes
Is it possible to implement such behaviour with asyncrun?
So for example i want to start http-server, start js/sass/less etc. preprocessor, run tests

Also it would be very great to see which processes are currently running in split window and to make some actions with those processes. For example we have 3 processes:
```viml
1 http-server
2 gulp
3 tests
```
Each one of them you can stop, restart, open quickfix window etc.

Feel free to close this issue if it doesn't fit the purpose of your plugin
Thank you for your work!

**Comment by skywind3000** [comment]
sorry, asyncrun is focusing on providing best experience in single background process.
In your case, maybe you need a tmux.

**Comment by deathmaz** [comment]
No problem, I'm already using tmux
