### ISSUE TITLE
Windows 下使用 -mode=4 时路径带空格会出现错误

### ISSUE THREAD

**Issue by NihilityT** [skywind3000/asyncrun.vim#121]
Windows 下使用 -mode=4 时如果路径带空格会出现错误，弹出的窗口会提示：
>'xxx' 不是内部或外部命令，也不是可运行的程序或批处理文件。

或

>系统找不到指定的路径。

而使用 -mode=2 则不会出现这个问题。

使用的命令为：
```
:AsyncRun -mode=[24] "$(VIM_ROOT)/$(VIM_FILENOEXT)"
:AsyncRun -mode=[24] "%:p:r"
```

**Comment by skywind3000** [comment]
解决了？怎么关闭问题了呢？

**Comment by skywind3000** [comment]
我试过了。windows 下路径带空格时 mode=4 工作正常。
