### ISSUE TITLE
AsyncRun not relinquishing quickfix window during jobs

### ISSUE THREAD

**Issue by badfilms** [skywind3000/asyncrun.vim#123]
When I run jobs that have quickfix output, I cannot move my cursor until the job is done.

That is, while I can move out of the quickfix window, it will immediately jump back.

While I have a heavily configured Vim environment, I have searched for conflicts and have been unable to find any that are obvious.

I am running Vim 8.1 within iTerm2.

**Comment by skywind3000** [comment]
there must be some plugins using autocmd to change your focus when updating quickfix .

**Comment by badfilms** [comment]
I oddly can't reproduce the error anymore, though in an effort to isolate conflicts, I removed YouCompleteMe from my plugins (as it was one of three possible candidates) and it seemed to do the trick, even though I have since re-added it.

I am at a loss. I'll close this for now but I may reopen if the problem returns so I can isolate it and hopefully find a permanent solution.
