### ISSUE TITLE
设置了g:asyncrun_open = 6  ， 怎么运行命令后 quickfix window 不会自动打开？

### ISSUE THREAD

**Issue by hawkinchina** [skywind3000/asyncrun.vim#129]
设置了g:asyncrun_open = 6  ， 怎么运行命令后 quickfix window 不会自动打开？
F10的快捷键，是可以，弹出/关闭quickfix window 的。。。

new option g:asyncrun_open to open quickfix window after job starts.

**Comment by fcying** [comment]
测试没问题, 可以正常打开

**Comment by ACXLM** [comment]
map <F5> :AsyncRun -raw python %   ， 一键运行后不会打开 quickfix window ，
设置如下， 使用快捷键可以打开 Quickfix 窗口 ， 但是buffer中没有任何消息
"asyncrun 设置
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" 自动打开 quickfix window ，高度为 6          
 let g:asyncrun_open = 6                        
" 任务结束时候响铃提醒                         
 let g:asyncrun_bell = 1                        
"运行前保存                                    
let g:asyncrun_save = 1                        
" 设置 F8 打开/关闭 Quickfix 窗口              
 nnoremap <F8> :call asyncrun#quickfix_toggle(6)<cr>
 let g:asyncrun_rootmarks = ['.svn', '.git', '.root', '_darcs', 'build.xml']
