### ISSUE TITLE
Feature Suggestion - Mark a File to Be Run

### ISSUE THREAD

**Issue by Neur1n** [skywind3000/asyncrun.vim#137]
I was following your work to build my own async-run tool, and I added a function to mark a file as the main file to run, so that the user does not always need to run the execute command (take `:call asyncrun#execute()` as an example) in the main file buffer. The file does not need to be present in the current buffers nor even hidden ones. Please checkout this [file](https://github.com/Neur1n/neurun/blob/master/autoload/neurun/config.vim) if you are interested. And again, this is not a feature request but a suggestion. Hope it benefits the users.

**Comment by skywind3000** [comment]
你这个用途太具体了，包括 `asyncrun#execute` 我也嫌弃它太具体了，所以迟迟没有正式放出来。这件事情感觉不是 AsyncRun 这一层该做的事情。我正在想新开个项目 asyncbuilder.vim/ asyncmaker.vim 之类的来调用 AsyncRun 做这个事情。

再，你这个标注主文件的解决方案其实不够完美，其实你要做的也只是针对分布再不同项目里的文件，做一些针对所属项目的事情，对吧？

我觉得 VsCode 的解决方案更高明一些，你需要在项目根目录下面新建一个 .vscode/launch.json 文件，里面定义了一系列针对本项目的 “动作”，比如编译和运行，那么 vscode 通过 .vscode 目录识别你正在编辑的文件属于哪个工程，并从 launch.json 里提取你之前针对该工程定义的 “动作” 来执行，不需要切换文件。

各种 ”动作“ 里不不但可以写清楚该项目主文件是啥，还可以标明各种参数和启动方式。这样是不是比标注主文件更 干净和灵活一些？

**Comment by skywind3000** [comment]
你也可以靠 Makefile 来做这个事情：

```VimL
nnoremap <silent> <F7> :AsyncRun -cwd=<root> make <cr>
nnoremap <silent> <F8> :AsyncRun -cwd=<root> -raw make run <cr>
nnoremap <silent> <F6> :AsyncRun -cwd=<root> -raw make test <cr>
nnoremap <silent> <F4> :AsyncRun -cwd=<root> cmake . <cr>
```

这样其实也就覆盖你的需求了，这几个快捷键会自动搜索你的项目根目录，并到项目根目录下运行 Makefile，你可以在 Makefile 的 run/test 等方法里写清楚对应命令是啥，包括你的主文件在哪里，调用参数是啥，但凡编辑这个项目目录下的任何文件，都可以用上面的快捷键执行到你的主文件，还可以保证每个项目都有不一样执行方式和启动参数（反正写在 Makefile 里嘛）。

是不是兼容性更强点？？

**Comment by Neur1n** [comment]
可能只是目前我的需求比较简单，所以设计得不够general purpose。在写这个之前我也用一个本地文件来设置，后来觉得需求不足以用一个文件，就改成标记了。期待你的新项目，学习一下。
