### ISSUE TITLE
rg 搜索不能运行

### ISSUE THREAD

**Issue by xizhong365** [skywind3000/asyncrun.vim#138]
用来运行 ripgrep 命令，没有成功搜索直接返回 code 1。

`:AsyncRun rg test`  返回 ` [Finished in 0 seconds with code 1]`
`:AsyncRun rg --vimgrep test`  返回 ` [Finished in 1 seconds with code 1]`

`:AsyncRun rg -h`  或者 `:AsyncRun rg --files` 都能正常工作。  

环境：
win10, vim 8.1

尝试删除其它插件以及配置，不行。

**Comment by skywind3000** [comment]
当前目录对了没有？？AsyncRun 运行的目录是 vim 的当前目录，即你运行：

    :pwd

显示的目录，你如果要 rg 在你当前编辑的文件下面找，你可以用：

    :AsyncRun -cwd=$(VIM_FILEDIR)   rg  test

你如果要 AsyncRun 在你的项目根目录下面运行，可以：

    :AsyncRun -cwd=<root>  rg test

项目根目录见文档定义。

**Comment by xizhong365** [comment]
谢谢回复。

`AsyncRun rg --files` 能正确列出当前目录下的文件。

确认目录：
`echo $VIM_CWD` ： D:\Dropbox
`echo $VIM_FILEDIR`: D:\Dropbox
`echo $VIM_ROOT`: D:\Dropbox

`AsyncRun -cwd=$(VIM_FILEDIR) rg test`: 仍然是 "1 files searched", g:asyncrun_status=failure。
`AsyncRun -cwd=<root> rg test`: 仍然是 "1 files searched", g:asyncrun_status=failure。这个目录是 git repo.

**Comment by skywind3000** [comment]
那你在终端下运行是啥情况呢？

**Comment by xizhong365** [comment]
powershell, git-bash 下rg 都能用，安装ack 插件使用 rg也行。
如果别人没出类似的问题，你就先不管吧。可能是我机器哪有问题。

**Comment by ykuun** [comment]
我也遇见了相同的情况 不知道目前是否有解决方案

**Comment by skywind3000** [comment]
后面加个点呢？

    :AsyncRun -cwd=<root> rg test .

**Comment by ykuun** [comment]
> 后面加个点呢？
> 
> ```
> :AsyncRun -cwd=<root> rg test .
> ```

可以正常使用，只是为啥当前pwd正常设置却需要额外的指定 cwd 以及 .
