### ISSUE TITLE
I try the asyncrun on my win10 gvim, it report the following error. 

### ISSUE THREAD

**Issue by irreallich** [skywind3000/asyncrun.vim#139]
my shell is msys64/usr/bin/bash of mingw64
and the gvim is 32bit version 
AsyncRun python %
and I try with cmd ls , it also report simlar issue.

log of copen:
|| [python aboutdlg.py]
|| /home/hwang29/work/tools/msys64/usr/bin/bash: C:/work/tools/msys64/tmpasyncrun.cmd: No such file or directory
|| [Finished in 1 seconds with code 127]

|| [ls]
|| /home/hwang29/work/tools/msys64/usr/bin/bash: C:/work/tools/msys64/tmpasyncrun.cmd: No such file or directory
|| [Finished in 1 seconds with code 127]

**Comment by skywind3000** [comment]
Your `shell` has been set to `bash` ?? why are you setting this in GVim ??

try:

    let g:asyncrun_shell='c:/windows/system32/cmd.exe'
    let g:asyncrun_shellcmdflag='/c'

**Comment by skywind3000** [comment]
In order to pass parameters correctly, a temp file is required on windows with the name:

    %TMP%\asyncrun.cmd

The default %TEMP% or %TMP% environment is:

    C:\Users\User\AppData\Local\Temp

so the default temp file should be:

    C:\Users\Linwei\AppData\Local\Temp\asyncrun.cmd

But it seems that your %TEMP% or %TMP% environment variable has been changed to:

    C:/work/tools/msys64/tmp

And the temp filename becomes:

    C:/work/tools/msys64/tmp\asyncrun.cmd

And somehow, back slash has been removed/escaped by bash, and the result becomes:

    C:/work/tools/msys64/tmpasyncrun.cmd

GVim is not designed for MSYS. if you set shell to msys's bash, many things may go wrong, not only asyncrun.

**Comment by skywind3000** [comment]
You can override the shell and shellcmdflag options in AsyncRun by:

    let g:asyncrun_shell="c:/windows/system32/cmd.exe"
    let g:asyncrun_shellflag="/c"

Then you can run windows command by AsyncRun in your gvim without modifying your `shell` and `shellcmdflag` options:

    AsyncRun dir

and you can call your bash by:

    AsyncRun C:\work\tools\msys64\usr\bin\bash -c "ls -la"

**Comment by irreallich** [comment]
在知乎上找到的文章了，我就用中文请教了
我现在在msys上使用gvim，配置环境各种奇怪问题，大多集中在win的 “” 以及/\之类的情况，请问以前遇到过这样的问题么？
另外msys的vim运行特别慢，你直到是什么原因么？
多谢

**Comment by skywind3000** [comment]
你这是好几个问题了。

## MSYS 下面用 GVim

根本没法混用，GVim 认为一个文件再 `d:\dev\source\hello.cpp` msys 认为文件在：`/d/dev/source/hello.cpp` 根本不通用。MSYS 认为文件在 `/home/user/work/hello.cpp`. 比如你 grep 了一个内容，输出到 GVim 的 quickfix 窗口，结果路紧名都是这些 /home 开头的，GVim 根本打不开。

## MSYS 下面的 Vim 慢

你 msys 下面的 Vim 是怎么安装的？

    pacman -S msys/vim

?? 慢是怎么慢？滚屏卡？按键响应不及时？麻烦你说详细点，否则没法给你诊断，你个来请教问题的，打的字还没我打的多。

**Comment by irreallich** [comment]
根本没法混用，GVim 认为一个文件再 d:\dev\source\hello.cpp msys 认为文件在：/d/dev/source/hello.cpp 根本不通用。MSYS 认为文件在 /home/user/work/hello.cpp. 比如你 grep 了一个内容，输出到 GVim 的 quickfix 窗口，结果路紧名都是这些 /home 开头的，GVim 根本打不开。

关于这个问题，我现在有一部分功能还可以使用。尽量使用vimgrep， 复杂的grep不再vim里执行，反正就是将就，正则表达基本上没法用，加了“”就各种问题，看了你的说明后，我考虑前夕会cmd，不过cmd里好多linux的命令用不了，把msys的bin加入后也有问题。
今天做实验的时候发现了一点，同样一个autoload里的函数，我在gvim启动的时候使用vimscript脚本调用时会报错，但是启动起来之后在命令模式下用：call 调用就没问题
下面时启动时的错误的log，可以看到shellcmdflag变成了 /c 而不是-c
C:/work/tools/msys64/usr/bin/bash /c curl -fLo ~/gvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
/c: /c: Is a directory
shell returned 126
Hit any key to close this window...

下面是代码
" plug settings
function! plugsetting#autoload() abort
    if !filereadable($VIMFILES.'/autoload/plug.vim')
        if env#Executable('curl') && env#Executable('git')
            if env#IsWindows()
                "exec ':!curl -fLo ' . $VIMFILES.'\\autoload'.'\\plug.vim ' .
                        \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
                exec "!curl -fLo ~/gvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"

            else
                silent! exec ':!curl -fLo ' . $VIMFILES.'/autoload'.'/plug.vim ' .
                            \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
            endif
        else
            echo "need curl!!"
        endif
    endif    
endfunction

**Comment by skywind3000** [comment]
补充：还要干掉 :set cursorline， :set cursorcolumn 最慢的两个

**Comment by irreallich** [comment]
非常感谢

**Comment by irreallich** [comment]
方便留个微信啥的，我这里刚开始学习vim，有问题方便向你请教

**Comment by skywind3000** [comment]
加 telegram 中文 vim 群：
https://t.me/VimHub

**Comment by skywind3000** [comment]
国内vim高手全在里面
