### ISSUE TITLE
run exe  with printf error

### ISSUE THREAD

**Issue by wining** [skywind3000/asyncrun.vim#14]
#include <stdio.h>
int main(int argc, const char *argv[])
{
    printf("a");
    printf("b");
    return 0;
}
Async gcc % -o a.exe
Async a.exe

Error detected while processing function <SNR>12_AsyncRun_Job_OnClose:
line 10:
E117:Unknown function: AsyncRun_Job_OnCallback
...
...
...

**Comment by skywind3000** [comment]
thanks, this is an issue introduced in last version, please update again, fixed.

**Comment by wining** [comment]
输出的结果还是不对

**Comment by skywind3000** [comment]
输出的结果是啥？

**Comment by wining** [comment]
输出了500多行，第一行乱码，其他都是.
是不是编码不对？

**Comment by skywind3000** [comment]
编码问题 `asyncrun_encs` 为gbk看看

**Comment by wining** [comment]
vimrc 添加 let g:asyncrun_encs = 'gbk' 还是一样的

**Comment by skywind3000** [comment]
能不能给个截图，多谢

**Comment by wining** [comment]
![6m7s7yq cgy3 373wit0_3](https://cloud.githubusercontent.com/assets/4005513/19592774/d55f2314-97af-11e6-9e34-b26b78a6dce0.png)

**Comment by wining** [comment]
现在这个插件不支持mac吗？

**Comment by skywind3000** [comment]
设置`asyncrun_trim`为1

**Comment by wining** [comment]
![h ap w 6r tij u_795 b](https://cloud.githubusercontent.com/assets/4005513/19593496/6e2cf0b4-97b3-11e6-9185-6ecead1db9a0.png)

**Comment by skywind3000** [comment]
没有调用fflush()
缓存着就退出了

**Comment by skywind3000** [comment]
fflush(stdout)

**Comment by skywind3000** [comment]
Vim什么版本啊？最近vim修了好几个job问题了

**Comment by wining** [comment]
哦，我更新下vim试试看

**Comment by wining** [comment]
mac上不能用吗？

**Comment by wining** [comment]
vim 8.0.2   有点老

**Comment by skywind3000** [comment]
都能用，macvim更新一下

**Comment by wining** [comment]
好的，多谢了

**Comment by skywind3000** [comment]
你的windows gvim之前用的哪个版本啊？

**Comment by wining** [comment]
8.0.2

**Comment by wining** [comment]
看到你的更新了，试了下，没问题了

**Comment by skywind3000** [comment]
能否用最新的 VIM和再更新一下 asyncrun，看看问题有无解决？

**Comment by skywind3000** [comment]
嗯，你试试把最后的fflush删除了看看。有无问题。

**Comment by wining** [comment]
去哪下载最新的啊？  fflush，我没有加，是正常的

**Comment by skywind3000** [comment]
哦，我是说C语言代码return前加flush，正常就好

**Comment by wining** [comment]
对，没加

**Comment by skywind3000** [comment]
windows gvim 开发C++的话，运行程序我推荐：

```VimL
noremap <F5> :AsyncRun -mode=4 "%<" <cr>
```

然后 F5运行你编译出来的程序。

**Comment by skywind3000** [comment]
比你vim里面 !main.exe 来运行你刚编译出来的程序体验好多了

**Comment by wining** [comment]
嗯，好，试试，3q

**Comment by wining** [comment]
额，原先的没好，只是第二行没输出出来
用你的运行方法也不错，但是汉字乱码

**Comment by wining** [comment]
我更新下vim，好了，应该是vim版本太低了 ^-^

**Comment by skywind3000** [comment]
quickfix汉字乱码要设置

    let g:asyncrun_encs = "gbk"

上面那个我推荐的运行方式 -mode=4是打开新的cmd窗口运行，完了按任意键结束，不是在quickfix中运行。

**Comment by wining** [comment]
quickfix 没乱码了，
noremap <F5> :AsyncRun -mode=4 "%<" <cr>
这种方法有乱码，也要设置？

**Comment by wining** [comment]
我没设置let g:asyncrun_encs  ，quickfix是正常的

**Comment by wining** [comment]
乱码应该跟vim没关系了，到时找找原因看看

**Comment by skywind3000** [comment]
嗯

**Comment by skywind3000** [comment]
既然问题解决，我想应该可以关闭了，这个表单
