### ISSUE TITLE
2.06 breaks RipGrep on Linux

### ISSUE THREAD

**Issue by bennyyip** [skywind3000/asyncrun.vim#140]
2.06 changes the way how stdin is handled. 
 https://github.com/skywind3000/asyncrun.vim/blob/master/plugin/asyncrun.vim#L679 sets `l:options['in_io']`  to 'pipe', which should be 'null' for rg.

**Comment by skywind3000** [comment]
恩，恢复了。

**Comment by skywind3000** [comment]
我稍微研究了一下，你如果 stdin=pipe 的情况下 rg foo 是会有问题的，然而：

    :AsyncRun rg  foo %:p:h

后面跟一个路径名的话，rg 就不需要依赖 stdin=null 了

**Comment by skywind3000** [comment]
或者你写明显点：

    :AsyncRun rg foo < /dev/null

**Comment by bennyyip** [comment]
https://github.com/bennyyip/dot-vim/commit/4e510142344719c58d87b26c164bfb5c0cf3b47f
我把路径加上了。

**Comment by skywind3000** [comment]
严格的讲，这一行：

    let l:cmd .= "@ rg -S --vimgrep " . a:args . ' ' . l:path

应该是：

    let l:cmd .= "@ rg -S --vimgrep " . a:args . '  "' . l:path . '"'

或者
    
    let l:cmd .= "@ rg -S --vimgrep " . a:args . ' ' . shellescape(l:path)

小心包含空格的参数。

**Comment by bennyyip** [comment]
谢谢，我改过来了
