### ISSUE TITLE
更新到最新版本rg 不能运行

### ISSUE THREAD

**Issue by abelZ** [skywind3000/asyncrun.vim#146]
最近把插件更新到最新版本，运行asyncrun rg --vimgrep word 命令立马返回finished in 1 seconds with code 1
终端下面运行所有rg命令都没问题，运行asyncrun rg不加任何参数也没有问题
vim里直接运行!rg --vimgrep word输出正常
可以确定的是之前的版本是ok的，因为重度使用这个功能
我的环境是win10 64bit gvim8.1 64bit

**Comment by skywind3000** [comment]
引入了一个新变量：

```VimL
let g:asyncrun_stdin = 0
```

即可

**Comment by abelZ** [comment]
感谢解答，完美解决，close
