### ISSUE TITLE
neovim 0.4 Error when execute asyncrun#quickfix_toggle

### ISSUE THREAD

**Issue by VDeamoV** [skywind3000/asyncrun.vim#149]
Error Message is following below.

The change I have done before error occurred:
1. install coc.nvim
2. install doc-python

Only quick fix_toggle have error, other function works fine

PS. `vim` works fine, only Neovim show the bug
```bash 
call asyncrun#quickfix_toggle(Error detected while processing function <SNR>19_load_all[6]..<SNR>19_imappings_load:
line   71:
E115: Missing quote: '\1'', '')
E116: Invalid arguments for function substitute
E15: Invalid expression: substitute(newkey, '\(^[^ ]*\) ', '\1'', '')
```

**Comment by skywind3000** [comment]
AsyncRun doesn't have `load_all` and `imappings_load` functions, it must belong to other plugins and triggerred by AutoCmd.
