### ISSUE TITLE
:AsyncRun的第一个字母能不能小写?

### ISSUE THREAD

**Issue by netroby** [skywind3000/asyncrun.vim#15]
:AsyncRun的第一个字母能不能小写?
:asyncRun 这样就免得打第一个字母的时候要按Shift键了. 我很懒

**Comment by tracyone** [comment]
非内嵌的vim命令，头个字母必须大写的😎

**Comment by skywind3000** [comment]
你 noremap 到一个快捷键上嘛，一键 git fetch，一键 go build
