### ISSUE TITLE
连续多个冒号导致的打印格式化时间字符串有问题

### ISSUE THREAD

**Issue by BewareMyPower** [skywind3000/asyncrun.vim#161]
Python代码
```python
print("2019-09-30 11:48:22")
```
输出
```
2019-09-30 11|48| 22
```
应该和冒号相关，简单测试了下
```python
print("1:2")
print("1:2:3")
print("1:2:3:4")
print("1:2:3:4:5")
```
`AsyncRun`打印结果依次为：
```
|| 1:2
1|2| 3
1|2 col 3| 4
1|2 col 3| 4:5
```
第3个冒号后就继续正常打印了，不太清楚什么原因导致的，有什么配置可以解决吗？

**Comment by skywind3000** [comment]
加 -raw 就不会和 errorformat 匹配了

:AsyncRun -raw python ...

没看文档么？写的清清楚楚。

**Comment by BewareMyPower** [comment]
> 加 -raw 就不会和 errorformat 匹配了
> 
> :AsyncRun -raw python ...
> 
> 没看文档么？写的清清楚楚。

对不起，确实没注意，谢谢。
