### ISSUE TITLE
no output of java job in win32

### ISSUE THREAD

**Issue by Konfekt** [skywind3000/asyncrun.vim#170]
When using my plug-in [vim-langtool](https://github.com/Konfekt/vim-langtool) (that calls the Java command-line program LanguageTool) with this plug-in and the command
```vim
command! -bang -nargs=* -complete=file -bar Make AsyncRun<bang> -auto=make -program=make
```
under Windows 10 x64, then `:LangTool` shows no output. This is in contrast to the `:Make` command given by [vim-dispatch](https://github.com/tpope/vim-dispatch) that works fine (albeit the encoding is off).

Everything works fine under Linux.

**Comment by skywind3000** [comment]
Please try:

```
let g:asyncrun_stdin = 0
```

**Comment by Konfekt** [comment]
Thank you! This setting is undocumented, though, it seems. At least in `doc/asyncrun.txt` it cannot be found.

**Comment by skywind3000** [comment]
Yes, it is used to decide if or not close stdin before job starts. by default, stdin is closed, but some tools like cmake on windows will check that and print errors (linux cmake won't). So  I set `g:asyncrun_stdin` to 1 on windows.

Another work around is calling langtools like:

    :AsyncRun java /path/to/langtools.jar  < /dev/nul

**Comment by Konfekt** [comment]
But isn't `< /dev/nul` for Unix and maybe `< nul` for Windows?

**Comment by Konfekt** [comment]
With `let g:asyncrun_stdin = 1` the output is, independent of appending `< NUL` or not, 
```
|| Working on STDIN...
```
With `let g:asyncrun_stdin = 0` the output is
```
|| Exception in thread "main" java.io.IOException: Stream Closed
|| 	at java.io.FileInputStream.readBytes(Native Method)
|| 	at java.io.FileInputStream.read(Unknown Source)
|| 	at java.io.BufferedInputStream.read1(Unknown Source)
|| 	at java.io.BufferedInputStream.read(Unknown Source)
|| 	at java.io.BufferedInputStream.read1(Unknown Source)
|| 	at java.io.BufferedInputStream.read(Unknown Source)
|| 	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
|| 	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
|| 	at sun.nio.cs.StreamDecoder.read(Unknown Source)
|| 	at java.io.InputStreamReader.read(Unknown Source)
|| 	at org.languagetool.tools.StringTools.readerToString(StringTools.java:255)
|| 	at org.languagetool.commandline.Main.getFilteredText(Main.java:348)
|| 	at org.languagetool.commandline.Main.runOnFile(Main.java:174)
|| 	at org.languagetool.commandline.Main.main(Main.java:466)
```

**Comment by skywind3000** [comment]
why was it trying to read data from stdin?

**Comment by Konfekt** [comment]
The [options](http://wiki.languagetool.org/command-line-options) do not explain why, therefore I asked about it at the repository of the program.

**Comment by skywind3000** [comment]
Could you provide the full command ? I will try in my environment.

**Comment by Konfekt** [comment]
It should be, on Windows 10 64bit,
```
let g:asyncrun_stdin = 0
let &makeprg='java -jar ~/LanguageTool/languagetool-commandline.jar --autoDetect ~/test.txt'
command! -bang -nargs=* -complete=file -bar Make AsyncRun<bang> -auto=make -program=make
Make
```

**Comment by Konfekt** [comment]
Perhaps you could explain at https://github.com/languagetool-org/languagetool/issues/2323#issuecomment-573402960 

> I cannot reproduce this on Linux with LT 4.8. `Working on STDIN...` is only printed when the filename equals `-`, so I guess the command you've given is not exactly the one that's actually running?

why somehow with AsyncRun.vim the file path argument is replaced by `-` ?

**Comment by Konfekt** [comment]
Perhaps it is due to AsyncRun.vim after all because vim-dispatch does not have this issue.

**Comment by skywind3000** [comment]
I will check that

**Comment by skywind3000** [comment]
Sorry, I can't reproduce your error, langtool works very well in my laptop (with or without stdin closed):

```VimL
let &makeprg='java -jar d:/software/LanguageTool/LanguageTool-4.8/languagetool-commandline.jar --autoDetect d:/test.txt'
AsyncRun -auto=make -program=make
```

see my screenshot:

![langtool](https://user-images.githubusercontent.com/3035071/72220000-2670b880-3587-11ea-8e5e-3caaee5faa8d.png)

**Comment by Konfekt** [comment]
Is it perhaps a matter of the &errorformat as set at https://github.com/Konfekt/vim-langtool/blob/061135e455b818a60dbf1a88206b4c8c0d35d5bd/compiler/langtool.vim#L29 ?

**Comment by Konfekt** [comment]
Thank you very much for your patience. Please excuse my oversight.

Probably
```vim
let g:asyncrun_wrapper = 'cmd.exe start /LOW'
```
will work fine. I will close this, as I deem such settings too experimental for asking for support.

**Comment by skywind3000** [comment]
When you are using “start” on windows, the current process will exit silently, langtool will run in a detached session (not the current conemu terminal environment) and its output  cannot be captured by AsyncRun.

**Comment by Konfekt** [comment]
Thank you for your explanation. Probably there is no safe way to execute a make command in Vim in low priority then in Windows.

**Comment by Konfekt** [comment]
This was a Vim issue. 
```vim
command! -nargs=* AsyncMake AsyncRun -auto=make -program=make <args>
AsyncMake "%"
```
works fine, but
```vim
command! -bar -nargs=* AsyncMake AsyncRun -auto=make -program=make <args>
AsyncMake "%"
```
produces this issue.
It only happens with double quotation marks around the file path and the `-bar` parameter on Windows.
Perhaps you can confirm?

**Comment by Konfekt** [comment]
For what it's worth, it works fine `let g:asyncrun_wrapper = 'start /B /LOW'`.

**Comment by skywind3000** [comment]
Great! Good for you.
