### ISSUE TITLE
`AsyncRun explorer.exe %` does not open file of current buffer on Windows 10

### ISSUE THREAD

**Issue by Konfekt** [skywind3000/asyncrun.vim#171]
on Windows 10 1909 64bit in gVim 8.1.2424 from https://github.com/vim/vim-win32-installer, `AsyncRun explorer.exe %` does not open file of current buffer but says that the command given by the path of the current file was not found. 
`AsyncRun explorer.exe %:S` opens explorer.exe. 

`explorer.exe %` and  `explorer.exe %:S` open the file even for paths with white spaces in them.

**Comment by skywind3000** [comment]
what about

    :AsyncRun explorer.exe "%:p"

**Comment by Konfekt** [comment]
This works, as does `exe 'AsyncRun explorer.exe ' . shellescape(expand('%'))`. 

Still, it differs from the behavior of `!explorer.exe` :

> - Easy to use, just start your background command by ':AsyncRun' (just like
  old "!" cmd).

**Comment by skywind3000** [comment]
The accurate way for this is :

    AsyncRun explorer.exe "$(VIM_FILEPATH)"

Because `%` is interpreted by vim itself. and if it contains spaces, a space will be translate into a backslash followed by a space.

**Comment by skywind3000** [comment]
There is a function form of asyncrun:

```VimL
call asyncrun#run(bang, opts, command)
```

see: [here](https://github.com/skywind3000/asyncrun.vim#function-api)

**Comment by Konfekt** [comment]
Thank you, I see that at https://github.com/skywind3000/asyncrun.vim#manual you warn about the expansion of `%` when it contains spaces.
