### ISSUE TITLE
Keep terminal color

### ISSUE THREAD

**Issue by tmpm697** [skywind3000/asyncrun.vim#172]
I run this command `:AsyncRun rustc % | ccat`. Is there a way to keep terminal output color of `rustc test.rs | ccat` command to quickfix window?

**Comment by skywind3000** [comment]
You need a real terminal, try this:

    AsyncRun -mode=term -pos=bottom rustc % | ccat

or 

    AsyncRun -mode=term -pos=tab rustc % | ccat

To run command in a internal terminal, note internal terminal also has insert/normal mode, if you want to manipulate the text (scroll, copy & paste, jump between windows), you need enter normal mode by `<c-\><c-n>`.

**Comment by skywind3000** [comment]
One side effect: it's not quickfix window, errors cannot be matched.

**Comment by tmpm697** [comment]
Nice, now this plugin became extremely usefull, I'd never leave vim again even I'm running tmux.
