### ISSUE TITLE
unix pipe support

### ISSUE THREAD

**Issue by pinggit** [skywind3000/asyncrun.vim#174]

**Comment by pinggit** [comment]
```
AsyncRun -mode=term -pos=bottom -rows=15 -cols=40 -focus=0 ls -lt | grep abc
```

目前不可以，请问如何做到？

**Comment by skywind3000** [comment]
不要加管道，要用管道的话，先写到一个文件里面，再调用。

**Comment by skywind3000** [comment]
vim 里面 

    :term ls -lt | grep abc

也没法用。

**Comment by pinggit** [comment]
感觉不能做到很奇怪。。同样是运行一个命令而已，只不过一个命令里面有管道，一个里面没有。有管道的命令为何不能运行呢？

**Comment by skywind3000** [comment]
这你要问 vim 去，我只是帮忙传参而已。

**Comment by pinggit** [comment]
我搞不太懂。。
在vim里我可以这样：
:!ls -lt | grep python

但是换了asyncrun:
:AsyncRun -mode=term -pos=bottom -rows=15 -cols=40 -focus=0 ls -lt | grep
-i markdown
ls: cannot access '|': No such file or directory
ls: cannot access 'grep': No such file or directory
ls: cannot access 'markdown': No such file or directory

我理解你的意思是，用了mode term， 是vim不支持向term里发的命令中含有管道 |
那么其他mode有可以支持管道的吗？

奇怪的是目前我的环境里只有mode term work了。其他的mode全都不work，这可能是我开的另外那个问题。。

**Comment by skywind3000** [comment]
我说的是 vim 的 `:term` 命令，你可以试试，一样不支持管道，传参是一个很精细的活，需要注意很多地方，复杂命令你可以写到临时脚本里再调用即可。

其他模式怎么可能没效果，你打开了 quickfix 窗口没有？设置下：

**Comment by pinggit** [comment]
打开quickfix之后在quickfix里work了。谢谢！

**Comment by pinggit** [comment]
送上我的星。
