### ISSUE TITLE
2/5/2020 版本的问题

### ISSUE THREAD

**Issue by pinggit** [skywind3000/asyncrun.vim#175]
我是今天安装的插件。现在按照readme里的操作都不能执行了。
比如
```
:AsyncRun grep -i solution %
```
没有反应。

但是
···
:AsyncRun -mode=term -pos=bottom -rows=15 -cols=40 -focus=0 grep -i solution %
···
可以。

这些参数没有缺省值吗？

**Comment by skywind3000** [comment]
你自己的 errorformat 没设置好吧，你试试

    :AsyncRun -raw grep -i solution %

呢？

**Comment by pinggit** [comment]
试了，也毫无反应。。

**Comment by skywind3000** [comment]
你打开了 quickfix 窗口没有？

**Comment by pinggit** [comment]
after I read the README.md more I understood. it works!
thanks.

AsyncRun displays its output in quickfix window, so if you don't use :copen {height} to open quickfix window, you won't see any output. For convenience there is an option g:asyncrun_open for you:

:let g:asyncrun_open = 8

Setting g:asyncrun_open to 8 will open quickfix window automatically at 8 lines height after command starts.
