### ISSUE TITLE
Disable command string and timing result 

### ISSUE THREAD

**Issue by slothropbodine** [skywind3000/asyncrun.vim#176]
Hello, thanks for the awesome plugin!

I'm having an issue Similar to #27 
When I run `AsyncRun make` i don't want to see the command string and timing result in the copen window. I am wanting to use `:cnext` and `cprev` to jump between errors but vim includes the following
```
|| [make]
|| [Finished in 2 seconds]
```
when I use those commands.

I tried `AsyncRun -raw` and the command string and timing result are still included. Is there anyway to disable echoing these? If not, is this a feature you would consider adding or accepting a pull request which adds it?

**Comment by skywind3000** [comment]
see the documentation for `-strip`:

:AsyncRun -strip ls -la

**Comment by slothropbodine** [comment]
Thanks so much! I don't know how I missed that in the docs.
