### ISSUE TITLE
Run task in background and echo out success or failure

### ISSUE THREAD

**Issue by webdavis** [skywind3000/asyncrun.vim#178]
Would it be possible to implement a couple of command line flags such as `AsyncRun -open=0 -echo-status` where `-open` prevents the quickfix from opening for that command and `-echo-status` echos out "Success" or "Failure"? (Or something similar.) This would make it easy to add a background runner to [vim-test](https://github.com/janko/vim-test) that is optimal for automatic test running. If you are open to something like this and don't have the time I would be happy to submit a pull request.

**Comment by skywind3000** [comment]
try:

```VimL
:AsyncRun -mode=hide echo 1234 > ~/output.txt
```

**Comment by webdavis** [comment]
The only problem with this is that it doesn't capture the output in the quickfix window. I would like to get the following scenario:

1. Run a command like `:Asyncrun mvn test -Dtest=employee.API.#` while temporarily setting g:asyncrun_open = 0`. 
2. Capture the output in the quickfix window.
3. Echo out one of the following messages to the message line in Neovim based on the exit code of the shell command:
  - `Success: !mvn test -Dtest=employee.API.#`
  - `Failure: !mvn test -Dtest=employee.API.#`

The way I see it, to accomplish this requires two things:
1. Capture the exit status of the shell command that was executed by `AsyncRun`.
2. Temporarily set `g:asyncrun_open = 0`.

That way if `Failure` is printed to the message line you can open the quickfix window and view the failed test, and if `Success` then continue hacking.

**Comment by skywind3000** [comment]
Fine, updated:

```VimL
:AsyncRun -open=0 ls -la
```

**Comment by webdavis** [comment]
Hopefully my pull-request to `vim-test` gets approved. Here is a video of the intended behavior:
[![asciicast](https://asciinema.org/a/306173.svg)](https://asciinema.org/a/306173)

**Comment by skywind3000** [comment]
An update you should know:

I have changed `-open=0` to `-silent`, because `-open=0` is hard to understand.

**Comment by skywind3000** [comment]
FYI again, there is also a `silent=1` option in `asynctasks.vim`:

https://github.com/skywind3000/asynctasks.vim/wiki/Task-Examples#silence-and-notify

**Comment by webdavis** [comment]
Nice! Could you implement a `-notify` option on the command line? That would clean up this [commit](https://github.com/janko/vim-test/commit/c4306da17a20e86b35cc686741cd2e6ca3157ff2#diff-52fe4cbf4297c73b5a08849fdfa5eb1cR56) quite a bit

**Comment by skywind3000** [comment]
It is implemented in `asynctasks.vim`, not asyncrun. I want to keep asyncrun more generic.

But you can still use:

```
:AsyncRun -post=call\ asynctasks#finish("echo")   ....
```

For this.

**Comment by webdavis** [comment]
Alright sounds good. I appreciate all the help.
