### ISSUE TITLE
Multi-line errorformat causes duplicated and missing output

### ISSUE THREAD

**Issue by idbrii** [skywind3000/asyncrun.vim#179]
I'm running python that hits an exception and my errorformat use a multiline error to process the traceback. When I use `:AsyncRun`, some output is duplicated and some is missing. If I use `:make`, then I see the correct output.

If I change my errorformat to be single-line, then I don't see any issues, so I assume matching multi-line messages (%A, %C, %Z) is the root of the problem. 

# Repro

c:/scratch/mytest.py
```python
print("hello")
raise Exception("bad")
```

~/.vim/reprovimrc.vim
```
" Isolate from my vim config. Using vim-sensible as baseline.
let s:plugins = ['sensible']
let s:plugins += ['asyncrun']

set runtimepath-=~/.vim
set runtimepath-=~/.vim/after
set runtimepath-=~/vimfiles
set runtimepath-=~/vimfiles/after
for plugin in s:plugins
    exec "set runtimepath^=~/.vim/bundle/". plugin
    exec "set runtimepath+=~/.vim/bundle/". plugin ."/after"
endfor
set viminfofile=NONE



" Setting up our testcase:

let &makeprg='python3 -t %' 

set errorformat=

" This single-line error works correctly with AsyncRun.
"~ set errorformat+=%\\s%#File\ \"%f\"\\,\ line\ %l\\,\ in%.%#
"~ set errorformat+=%*\\s\ \ \ %m

" This does not. But it works with :make
set errorformat+=%A%\\s%#File\ \"%f\"\\,\ line\ %l\\,\ in%.%#
set errorformat+=%Z%*\\s\ \ \ %m

let g:asyncrun_open = 30
nnoremap \\ :<C-u>AsyncRun -program=make -auto=make @<CR>

" With or without this line, issue still occurs.
let $PYTHONUNBUFFERED=1
```
Commands:
```
> gvim -Nu ~/.vim/reprovimrc.vim -U NONE c:/scratch/mytest.py

:AsyncRun -program=make -auto=make @

Output:
|| [python3 -t scratch\mytest.py]
|| hello
|| Traceback (most recent call last):
scratch\mytest.py|2|  raise Exception("bad")
|| [python3 -t scratch\mytest.py]
|| hello
|| Traceback (most recent call last):
scratch\mytest.py|2| 

:make
Output:
|| hello
|| Traceback (most recent call last):
scratch\mytest.py|2|  raise Exception("bad")
|| Exception: bad
```

Why does the asyncrun output have `[python3 -t scratch\mytest.py]` twice and is missing the `Exception: bad` output?

Using raw (`:AsyncRun -program=make -raw -auto=make @` ) shows the correct output (but no efm).

Here's the raw output:

```
|| [python3 -t scratch\mytest.py]
|| hello
|| Traceback (most recent call last):
||   File "scratch\mytest.py", line 2, in <module>
||     raise Exception("bad")
|| Exception: bad
|| [Finished in 0 seconds with code 1]
```

# Versions

* asyncrun a7ebec5f5097c46a3ee4503d8c9bfb989a8ff773
* sensible tpope/vim-sensible@7aa7dba2a2594c209d8063c4c1c56de130c362d3
* Windows 10
* VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 26 2020 23:02:14)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-324

**Comment by skywind3000** [comment]
Because asyncrun feeds output line by line to quickfix. But make feeds them all together.

So multiline errorformat doesn't work very well.
