### ISSUE TITLE
Trigger autocommand QuickFixCmdPost

### ISSUE THREAD

**Issue by embear** [skywind3000/asyncrun.vim#18]
Hi,

thanks for the great plugin. Works really fine for me. Except one things: I run `make` through asyncrun and I additionally use the plugin errormarker (https://github.com/vim-scripts/errormarker.vim) that highlights compiler errors and warnings after a `make` using the `QuickFixCmdPost`. This does not work for asyncrun. Is it possible to add a `doautocmd` after asyncrun detects the exit of the called program? For now I added the following line as last command in `AsyncRun_Job_OnFinish`:

```viml
silent doautocmd QuickFixCmdPost make
```

The hard coding of `make` is really silly but I don't know how it could be implemented in a intelligent way. Any Ideas?

**Comment by skywind3000** [comment]
If you have read the whole document you can find there are two way to trigger it without modifing the source code:

**First: using `g:asyncrun_exit` as global callback:**

    g:asyncrun_exit - script will be executed after finished

You can simply add a few code to your `vimrc`:

```VimL
let g:asyncrun_exit = "silent doautocmd QuickFixCmdPost make"
```

The script in `g:asyncrun_exit` will be triggered when any command is completed.
(will affect all the commands).

**Second: using `-post` option to indicate a vimscript to be executed**

```VimL
:AsyncRun -post=silent\ doautocmd\ QuickFixCmdPost\ make @ make
```

The vimscript in `-post` will be executed when this command is over. (won't affect other commands)

.......

You can use either `g:asyncrun_exit` or `-post` in your case without modifing any code in asyncrun.vim.

**Comment by embear** [comment]
Sorry, you are right. I should have read the whole documentation but I overlooked the part at the plugin header. Maybe it is a good idea to move it to the doc/asyncrun.txt file?

Anyway. Possibly it is worth a second thought to trigger the standard `QuickFixCmdPre` and `QuickFixCmdPost` auto commands when modifying the quickfix window.

**Comment by skywind3000** [comment]
I will inspect these two command, see if there is any potential conflict to other plugins, If QuickFixCmdPre and QuickFixCmdPost are scheduled by a long time running background job system.

**Comment by embear** [comment]
Possibly http://github.com/xolox/vim-tools.git can help here. I use it for my localvimrc plugin. I just maintain README.md and convert that to vim help using `html2vimdoc -f localvimrc README.md >doc/localvimrc.txt`. HTH.

**Comment by skywind3000** [comment]
that's cool, thanks

**Comment by embear** [comment]
Ah right. There was this issue. I forgot about it and never reported it to the author. I just commented out line 87 in the python script ;-) After that it just works.

**Comment by skywind3000** [comment]
In the latest version (1.3.5), there is a new option named "g:asyncrun_run" to enable QuickFixCmdPre / QuickFixCmdPost for you . 

If you setup like this:

```VimL
:let g:asyncrun_auto = "make"
```

"QuickFixCmdPre make" and "QuickFixCmdPost make" will be invoked before and after a background job's lifecycle.

**Comment by embear** [comment]
Thanks for adding the options. I tried both of them but prefer the `-auto=?` version because I just want to enable QuickfixCmd* for my `Make` but not for `Ctags`.

**Comment by skywind3000** [comment]
Thanks for feedback, glad to hear that the option is useful.
