### ISSUE TITLE
Feature request: make pos=tab obey focus=0

### ISSUE THREAD

**Issue by webdavis** [skywind3000/asyncrun.vim#181]
Would you be open to implementing terminal mode with `pos=tab` to obey `focus=0` such that when the command:

`AsyncRun -mode=term -pos=tab -focus=0 echo 1234`

runs a command in a new tab, but does not switch focus to it.

**Comment by skywind3000** [comment]
Reasonable feature:

updated: https://github.com/skywind3000/asyncrun.vim/releases/tag/2.5.5

**Comment by webdavis** [comment]
Thank you. It looks like `-post=` doesn't work with it. Is this the intended behavior?

**Comment by webdavis** [comment]
Also it doesn't look like it obeys the `g:asyncrun_exit` global, such that:

```vim
let g:asyncrun_exit = "silent call system('paplay ~/.vim/sounds/dialog-information.oga &')"
```

doesn't play a sound.

**Comment by skywind3000** [comment]
Still unimplemented, before that you can play the sound by [command modifier](https://github.com/skywind3000/asyncrun.vim#command-modifier) like :

```VimL
let g:asyncrun_program = get(g:, 'asyncrun_program', {})
let g:asyncrun_program.sound = { opts -> opts.cmd . ' ; paplay  "~/.vim/sounds/xx.mp3" ' }
```

It will append `paplay` command after your original command if `-program=sound` is provided.

usage:

```VimL
:AsyncRun -program=sound   xxx
:AsyncRun -mode=term -pos=tab -focus=0 -program=sound  xxx
```

one more step, different result with different sound:

     opts.cmd .  ` && paplay "success.mp3" || paplay "failure.mp3" '

**Comment by webdavis** [comment]
I see, that works. Are you planning on implementing `post` with terminal?

**Comment by skywind3000** [comment]
maybe later.

**Comment by webdavis** [comment]
Alright sounds good. I appreciate it greatly. I will be able to provide an `asyncrun_background_term` option for `vim-test` users once it's implemented.

**Comment by skywind3000** [comment]
`-post=xxx` is available for terminal tasks: https://github.com/skywind3000/asyncrun.vim/releases/tag/2.6.0

**Comment by webdavis** [comment]
Thank you!

**Comment by skywind3000** [comment]
FYI:

- a new position, upper case `TAB`, when `-pos=TAB` is provided, a new tab will be created on the left of current tab, it is useful because if the program exit and you close the terminal tab you will return to the previous tab like fzf.

- more examples in [wiki](https://github.com/skywind3000/asyncrun.vim/wiki/Customize-Runner) about new runners to run command in another tmux split or a new gnome-terminal window/tab.

**Comment by webdavis** [comment]
Very helpful!
