### ISSUE TITLE
quickfix  number characters limit

### ISSUE THREAD

**Issue by Burlter** [skywind3000/asyncrun.vim#182]
I code on python and when i write print() with long array, that takes more than 1024 chars on quickfix split, 1025 char and others do not show.

**Comment by skywind3000** [comment]
Try

    AsyncRun -mode=term xxx

**Comment by Burlter** [comment]
no way to lengthen the line?

**Comment by skywind3000** [comment]
No way, you would reformat your python output. use something like pretty print
