### ISSUE TITLE
Option shellslash Breaks AsyncRun

### ISSUE THREAD

**Issue by jgehrig** [skywind3000/asyncrun.vim#184]
On Windows, the `shellslash` option is not compatible with AsyncRun.

**Example `minimal.vim`:**
```
" Excluding plugin manager initialization overhead (Vundle).
Plugin 'skywind3000/asyncrun.vim'
set shellslash
```

**Example Scenario:**
1. Open Neovim: `nvim -u minimal.vim`
2. Run a command: `:AsyncRun echo "Hello World!"`
3. Open QuickFix: `:copen`
4. Notice error message.

```
|| [echo "Hello World!"]
|| ''C:' is not recognized as in internal or external command,
|| operable program or batch file.
|| [Finihsed in 0 seconds with code 1]
```

The `shellslash` options makes working with a few Windows-unfriendly programs easier... It would be nice to have AsyncRun properly adjust for this setting.

I will do some further debugging of this issue...

**Comment by skywind3000** [comment]
updated: 
https://github.com/skywind3000/asyncrun.vim/releases/tag/2.7.0

**Comment by jgehrig** [comment]
Thanks @skywind3000... You're fast!

I pulled the latest changes, and everything appears to be working 👍
