### ISSUE TITLE
Is there a way to open quickfix vertially?

### ISSUE THREAD

**Issue by stokhos** [skywind3000/asyncrun.vim#186]
Hi skywind3000:

I'm wondering if there is a way to open the quickfix window vertically?

Best

**Comment by mihaicristiantanase** [comment]
I did not find any solution in `asyncrun`, but you can do it in vim by running:
`:vertical 80copen`
This will show/move the quickfix window in a vertical split. Any `asyncrun` action you run will be displayed there.

**Comment by skywind3000** [comment]
Open it as your like in autocmd:

    autocmd User AsyncRunStart   YOU_COMMAND_HERE

remember to clear g:asyncrun_open.
