### ISSUE TITLE
Problem with grep

### ISSUE THREAD

**Issue by LemonBoy** [skywind3000/asyncrun.vim#19]
I haven't managed to find some time to track down the problem myself but sometimes the results get added to the quickfix list as unstructured entries, as if `efm` isn't set. I've attached a minimal vimrc, here's the steps to (hopefully) reproduce the issue:

- `Grep <TERM>`
- `:copen`
- The entries are correctly formatted
- Open the first result
- `Grep <TERM>`
- The entries are not formatted anymore

```viml
set nocompatible
call plug#begin('~/.vim/bundle')
Plug 'skywind3000/asyncrun.vim'
call plug#end()
let &grepprg='ag --vimgrep -- $*'
let grepformat='%f:%l:%c:%m'
command! -nargs=* Grep execute 'AsyncRun! -program=grep "'.escape(<q-args>, "|\%#'\ \"").'" .'
```

**Comment by skywind3000** [comment]
Because `:caddexpr` uses the global value of errorformat forever rather than local value of errorformat or grepformat.

you can add it to your global errorformat:

```VimL
set errorformat+=%f:%l:%c:%m
```

**Comment by LemonBoy** [comment]
I get the same result if I add the pattern to `efm` in the vimrc, the `efm` gets reset somehow

**Comment by skywind3000** [comment]
what does `efm` reset to ?
is `efm` modified some where after your vimrc ?
could you please just try to set `efm` directly in ex-cmdline after enter vim ?

**Comment by LemonBoy** [comment]
After some digging I found out that the `efm` is being reset by a `ftplugin` that defines a couple of `au`, one of which sets the `efm` directly.
I guess asyncrun is fine :)
