### ISSUE TITLE
Pandoc option not recognized in task.ini file

### ISSUE THREAD

**Issue by tkolleh** [skywind3000/asyncrun.vim#191]
The `--metadata-file` option is not recognized as part of the below command. The screenshot demonstrates that the command is valid from the terminal (zsh). 

```vim
command:markdown,md,pandoc=pandoc --standalone --verbose -f markdown -t html --metadata-file="/Users/tkolleh/Documents/metadata.yaml" --output="$(VIM_FILENOEXT).html" "$(VIM_RELNAME)" 
```

```c
pandoc --standalone --verbose -f markdown --output="project4-report.html" --metadata-file="/Users/tkolleh/Documents/metadata.yaml" "project4-report.md"
```

<img width="1083" alt="Screen Shot 2020-04-16 at 3 59 27 PM" src="https://user-images.githubusercontent.com/3095197/79501564-3ff92480-7ffc-11ea-8c9a-eabfec2baaba.png">

**Comment by skywind3000** [comment]
check if you have two pandoc executables in different path and use the absolute path for it.

**Comment by tkolleh** [comment]
🤦🏾‍♂️...Yep that was the issue. Seems that neovim is not referencing the alias. 

```c
 type pandoc
pandoc is an alias for /usr/local/opt/pandoc/bin/pandoc
```

**Comment by skywind3000** [comment]
shells has four modes:

- interactive or non-interactive.
- login or non-login

https://www.vanimpe.eu/2014/01/18/different-shell-types-interactive-non-interactive-login/

Your shell setup may only defined for an login+interactive shell, but vim/neovim start process in an 
non-login+non-interactive shell.
