### ISSUE TITLE
终端的背景色在异步运行命令后不能填充整个终端窗口

### ISSUE THREAD

**Issue by gVimer** [skywind3000/asyncrun.vim#195]
WIndows下 gVim8.2 我设置的了终端的背景色
highlight Terminal  GUI=BOLD   GUIBG=BLACK   GUIFG=WHITE 
然后运行一个一个Py文件 命令如下(映射的快捷键一键运行) 
 execute "AsyncRun -mode=term -pos=bottom -rows=10 -focus=0 Python %"
输出后 终端窗口有一部分没有被设置的黑色填充 具体看截图
![QQ截图20200524170524](https://user-images.githubusercontent.com/6241431/82750153-c6b1d600-9de0-11ea-8315-5ae015f77eb8.png)

**Comment by gVimer** [comment]
还有就是运行上面的命令 整个VIM会闪屏一下 但如果是输出到quickfix的话就存在这个问题

**Comment by gVimer** [comment]
还有就是-mode=term 模式下 无法用AsyncStop中断任务

**Comment by skywind3000** [comment]
那是配色问题，nontext 的颜色不是黑色，这不归 asyncrun 管
