### ISSUE TITLE
alias in .zshrc doesn't work

### ISSUE THREAD

**Issue by GopherJ** [skywind3000/asyncrun.vim#198]

**Comment by skywind3000** [comment]
https://askubuntu.com/questions/879364/differentiate-interactive-login-and-non-interactive-non-login-shell

**Comment by GopherJ** [comment]
ok thanks

**Comment by cnlzxin** [comment]
put your alias in `~/.zshenv`, [this question](https://stackoverflow.com/questions/22055613/zshell-aliases-like-gst-inside-vim) helps me.
