### ISSUE TITLE
Running commands in the right environment

### ISSUE THREAD

**Issue by sgoodwin** [skywind3000/asyncrun.vim#2]
Hi!

First off, thanks for this plugin, it's fun to play with.

I'm trying to use it to run my Xcode builds from Xcode's command line tool and it works for the simplest case but starts to fail when I try to set environment variables and such before the command. Get errors saying "command not found" or even sometimes it will just hang until I interrupt it in vim.

My best guess is that commands aren't being run in the same user/shell/environment I'm operating in. Is that true? It's a bit hard to tell from reading the code (I'm new to vimscript)

For reference, I'm trying to run commands like these:

```set -o pipefail;NSUnbufferedIO=YESxcrun xcodebuild build -project './TheoryDrills.xcodeproj' -scheme 'TheoryDrills' -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty --color```

Where the simpler case does work:

```xcodebuild -project './TheoryDrills.xcodeproj' -scheme 'TheoryDrills' -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty --color```

Any tips/clues/help you could give would be awesome.

Also, in case it's helpful, this is the plugin which generates the command: https://github.com/gfontenot/vim-xcode/blob/master/plugin/xcode.vim#L132-L135. I'm trying to use AsyncRun as the runner.

**Comment by skywind3000** [comment]
Arguments are splited by space, therefor, if a argument contains space in it, it should be escaped as backslash + space (same as ex command in vim).

This is a little difference between vim ex command & shell command, but Most of the time it's just alright. 

For your case, the right form of "platform=iOS Simulator,name=iPhone 6s"  is "platform=iOS\ Simulator,name=iPhone\ 6s".

As a simple way, you can write a shell script named xbuild.sh to achieve the same thing, and put your complex script into xbuild.sh , and use :AsyncRun to launch it.

**Comment by skywind3000** [comment]
Are you using MacVim from launch pad ? if so, environment variables are different from terminal vim. it could be solved by:
1. start macvim from terminal 
2. using vimrc to initialize system variables just like terminal:
```VimL
let $PATH='.....' . $PATH
```

**Comment by sgoodwin** [comment]
I'm using vim from the command line, no MacVim, so it should use the same environment variables as my terminal session right?

**Comment by skywind3000** [comment]
Yes, environment variables in terminal will be inherited in  vim and its child processes.

**Comment by skywind3000** [comment]
try to write a shell script to run xcodebuild, does it work for you ?

**Comment by sgoodwin** [comment]
I think I'm figuring it out. Looks like the problem involves quote marks and where they belong

**Comment by sgoodwin** [comment]
Got something working. Thank you!
