### ISSUE TITLE
asyncrun not playing well with command buffer

### ISSUE THREAD

**Issue by thraen** [skywind3000/asyncrun.vim#20]
Hi, 
asyncrun doesn't work well when invoked from the command window (I use `nnoremap : q:i`).
If I try to open the command window again after invoking a longer AsynRun I get lots of error messages, rendering the command window unusable until the run is finished.

**Comment by skywind3000** [comment]
please provide an example

**Comment by thraen** [comment]
it happens when I open the command window
`q:`
and start a longer asyncrun like:
`AsyncRun grep -r /* something`
and the open the command window again before the command finished.

**Comment by skywind3000** [comment]
fixed, you can try the latest version.

**Comment by thraen** [comment]
it works. Thanks!

**Comment by skywind3000** [comment]
so, this should be closed
