### ISSUE TITLE
The plugin conflict with vim-go

### ISSUE THREAD

**Issue by hbuxiaofei** [skywind3000/asyncrun.vim#201]
If  plugin `vim-go` insatlled, Quickfix show nothing with running `AsyncRun  <cmd>`  when open  `*.go` file.

The bug may be related with *efm* in function *AsyncRun_Job_Update*.

Ref:  https://github.com/fatih/vim-go

**Comment by skywind3000** [comment]
因为 vim-go 做了太多自作主张的事情了，比如私自篡改 errorformat，某些 errorformat 选项会过滤掉所有 quickfix 的输出。

你可以：

    :AsyncRun -raw command

忽略所有 errorformat，不匹配任何规则，直接输出原始内容到 quickfix 或者

    :AsyncRun -errorformat=xxx  command

自己在参数里指明使用什么 errorformat。

或者干脆点，自己加个 autocmd ，每次载入 go 文件时，重新设置一下被 vim-go 修改过的 errorformat。

**Comment by hbuxiaofei** [comment]
已经发现了，设置 
```
AsyncRun  -raw=1  ls
```
能正常显示。谢谢！
