### ISSUE TITLE
Compile and run oneliner?

### ISSUE THREAD

**Issue by TornaxO7** [skywind3000/asyncrun.vim#208]
Hello! I have this mapping:
```vim
nnoremap <leader>gd :AsyncRun gcc % <bar> :AsyncRun -raw -cwd=$(VIM_FILEDIR) ./a.out<CR>
```
When I'm running this shortcut, than it returns this error message:
```vim
|| [gcc Test3.c | :AsyncRun -raw -cwd=/my/path ./a.out]
zsh|1| command not found: :AsyncRun
|| [Finished in 0 seconds with code 127]
```
How can I compile and run the file afterwards?

**Comment by skywind3000** [comment]
nnoremap <leader>gd :AsyncRun -raw -cwd=$(VIM_FILEDIR)  gcc % && ./a.out<CR>

**Comment by TornaxO7** [comment]
Dayum. Haha I forgot that this "option" `&&` exists xD Thank you!
