### ISSUE TITLE
Vim hangs in infinity loop with printf (language: C) command

### ISSUE THREAD

**Issue by TornaxO7** [skywind3000/asyncrun.vim#211]
This is a minimal example in C:
```c
#include <stdio.h>
#include <stdlib.h>

int main () {

    while (1) {
        printf("Houston, we've a problem...\n");
    }

    return EXIT_SUCCESS;
}
```
If I run it with this command:
```vim
:AsyncRun -mode=async -cwd="$(VIM_FILEDIR)" -save=2 gcc % && ./a.out
```
than vim hangs up and the memory usage increases until my pc hangs up unless I kill the process manually.

The moment when you see the output at bottom appears if I hit `Ctrl + c`. I can't stop it with `:AsyncStop` since `(neo)vim` is stuck.

![GIF](https://user-images.githubusercontent.com/50843046/97441197-bc17e180-1928-11eb-8227-148a3b92a223.gif)

**Comment by skywind3000** [comment]
try

    :AsyncRun -mode=term -pos=tab -cwd="$(VIM_FILEDIR)" -save=2 gcc % && ./a.out

**Comment by TornaxO7** [comment]
It's working with your command now and I can cancel it with `Ctrl+c`, thanks! But it'd be nice if I could see the output at the bottom ^^ should I close this issue?

**Comment by skywind3000** [comment]
neovim's quickfix is inefficient, and job api is lack of flow control.
asyncrun has nothing to do with it.

**Comment by TornaxO7** [comment]
Ok, thanks for the information!
