### ISSUE TITLE
in term mode ,  Is there any way to show a popup  window .  like  work with  floaterm? 

### ISSUE THREAD

**Issue by WillDawnlll** [skywind3000/asyncrun.vim#213]
ps...thanks for this plug , now is enough to use, popup just for a litter cool....

**Comment by skywind3000** [comment]
Yes, see:

- https://github.com/skywind3000/asyncrun.vim/wiki/Customize-Runner 
- https://github.com/voldikss/vim-floaterm#asynctasksvim

**Comment by WillDawnlll** [comment]
thanks..
