### ISSUE TITLE
Chinese characters cannot be displayed properly when running asyncrun with `-mode=term`

### ISSUE THREAD

**Issue by Dekay999** [skywind3000/asyncrun.vim#220]
When I run a python file with 
```
:AsyncRun -mode=term -pos=bottom -raw python %
```
Chinese character cannot be displayed properly:
![image](https://user-images.githubusercontent.com/37211395/106236307-850ee000-6237-11eb-8f64-9475bb78d71e.png)

**Comment by skywind3000** [comment]
:AsyncRun -mode=term -pos=external -raw python %

**Comment by Dekay999** [comment]
Hi skywind, by using `-pos=external`, I got this:
![image](https://user-images.githubusercontent.com/37211395/106241680-66ade200-6241-11eb-8dfd-84e179bec684.png)
still, chinese character can't be displayed properly.

**Comment by skywind3000** [comment]
what your file encoding

**Comment by Dekay999** [comment]
utf-8

**Comment by skywind3000** [comment]
add a header to your python source:

    # -*- coding: utf-8 -*-

**Comment by Dekay999** [comment]
![image](https://user-images.githubusercontent.com/37211395/106243523-84307b00-6244-11eb-95b1-fb8e45fe670e.png)

![image](https://user-images.githubusercontent.com/37211395/106243492-77138c00-6244-11eb-9626-377a56ed3b6d.png)
 still the same output... By the way, I was using MSYS2 in windows10 system.

**Comment by Dekay999** [comment]
And if I run python in the Terminal, everything is OK:
![image](https://user-images.githubusercontent.com/37211395/106243894-1769b080-6245-11eb-9566-3520ee870c67.png)
So, this is really weird.

**Comment by skywind3000** [comment]
你别告诉我你是在用 windows 下的 gvim 操作 msys

**Comment by Dekay999** [comment]
哈哈, 原来是中国人, 我是在windows下装了MYSYS2, 在MSYS2里面用pacman装了vim

**Comment by Dekay999** [comment]
我是用的MSYS2终端, 那可能是MSYS2本身的编码问题, 我再研究研究, 多谢了

**Comment by skywind3000** [comment]
不知道了，有点诡异。

**Comment by Dekay999** [comment]
解决了, 确实是MSYS2的问题:
[](http://www.voidcn.com/article/p-fwtsrsaj-bph.html)

**Comment by Dekay999** [comment]
刚才的办法还有问题, 会把.py文件中的中文变成乱码(因为MSYS2和.py编码文件不一致), 用下面的办法终于可以完美解决了:
编写/bin/win文件如下
```
#!/bin/bash
$@ |iconv -f gbk -t utf-8
```
然后使用asyncrun时在python前面加上win:
```
:AsyncRun -mode=term -pos=bottom -raw win python %
```
现在就正常了. `/bin/win`脚本的作用是把一个终端的编码转化为utf-8编码再输出.

**Comment by skywind3000** [comment]
你用 msys 里面的 python 不就行了？

**Comment by Dekay999** [comment]
你说的对, 我刚刚试了, 直接安装pacman版本的python就没有这个问题了😂

**Comment by skywind3000** [comment]
下次提 issue 应该先把自己运行环境，vim 版本号什么说清楚。
