### ISSUE TITLE
update info on compatibility with fugitive

### ISSUE THREAD

**Issue by Konfekt** [skywind3000/asyncrun.vim#222]
The [wiki entry on vim-fugitive](https://github.com/skywind3000/asyncrun.vim/wiki/Cooperate-with-famous-plugins#fugitive) is out of date since https://github.com/tpope/vim-fugitive/commit/d4bcc75ef6449c0e5592513fb1e0a42b017db9ca

Instead custom commands

```vim
    command! -bang -bar -nargs=* Gpush execute 'AsyncRun<bang> -cwd=' .
          \ fnameescape(FugitiveGitDir()) 'git push' <q-args>
    command! -bang -bar -nargs=* Gfetch execute 'AsyncRun<bang> -cwd=' .
          \ fnameescape(FugitiveGitDir()) 'git fetch' <q-args>
```

must be added.

**Comment by skywind3000** [comment]
fixed, thanks

**Comment by Konfekt** [comment]
Now `FugitiveGitDir` returns the path of the `.git` subdir instead of that of the repository. To make the custom commands work again, replace  in all lines 

`fnameescape(FugitiveGitDir())` by `fnamemodify(FugitiveGitDir(), ":h:S")`.
