### ISSUE TITLE
-cwd="$(VIM_FILEDIR)" breaks

### ISSUE THREAD

**Issue by TornaxO7** [skywind3000/asyncrun.vim#223]
Example code (language: `C`):
```c
#include <stdio.h>
#include <stdlib.h>

int main()
{
    printf("Hi\n");
    return EXIT_SUCCESS;
}
```
Run with:
```bash
:AsyncRun -mode=term -pos=tab -cwd="$(VIM_FILEDIR)" -save=2 gcc -lm % && ./a.out
```
Getting the following error message:
![image](https://user-images.githubusercontent.com/50843046/112771594-d7e4f800-902c-11eb-9afa-4bccef04327c.png)

It works, if I remove the `-cwd="$(VIM_FILEDIR)` part of the command.

**Comment by skywind3000** [comment]
remove your quotation:

    :AsyncRun -mode=term -pos=tab -cwd=$(VIM_FILEDIR) -save=2 gcc -lm % && ./a.out

**Comment by TornaxO7** [comment]
It works, thank you!

**Comment by skywind3000** [comment]
also I updated asyncrun.vim to mute this error.

**Comment by skywind3000** [comment]
I found a bug in your command, `%` will be interpreted to a file name relative to vim's working directory, if you specify a different directory by `-cwd=?`, the `%` should be replaced as `$(VIM_FILENAME)', the correct version is:

    :AsyncRun -mode=term -pos=tab -cwd=$(VIM_FILEDIR) -save=2 gcc -lm "$(VIM_FILENAME)" && ./a.out

**Comment by TornaxO7** [comment]
I had no problems with this command yet, so I didn't change it but thank you for this hint!
