### ISSUE TITLE
mode模式为term时，无法异步执行

### ISSUE THREAD

**Issue by VimWei** [skywind3000/asyncrun.vim#225]
" 使用AsyncRun输出结果，好像无法异步——从用户使用体验角度看，只能等待执行结束才能动光标位置
`execute 'AsyncRun! -mode=term -pos=right -raw python "$(VIM_FILEPATH)"'`

" 相比之下，使用AsyncRun 及 vim-terminal-help输出结果，可以异步——未执行结束即可移动光标位置
`execute 'AsyncRun! -mode=term -pos=thelp -raw python "$(VIM_FILEPATH)"'`

PS：使用环境为 win 10, gvim 8.2

**Comment by skywind3000** [comment]
这是当前焦点是终端窗口，光标是终端控制，你要 `<c-\><c-n>` 将终端切换到 normal 模式才能移动或者切换。
