### ISSUE TITLE
不会配置，求个大神，帮我配一下python的errorformat

### ISSUE THREAD

**Issue by taotaoyihao** [skywind3000/asyncrun.vim#227]
这里是我的task.ini和quickfix的python的错误
![5371623338627_ pic_hd](https://user-images.githubusercontent.com/52092094/121552801-53a6ec00-ca43-11eb-8926-b2b0b92c11a9.jpg)
![5381623338630_ pic_hd](https://user-images.githubusercontent.com/52092094/121552807-5570af80-ca43-11eb-9c86-c8da7f55990e.jpg)

**Comment by taotaoyihao** [comment]
不会跳转到错误的地方

**Comment by skywind3000** [comment]
我也写不来 python 的错误解析

**Comment by taotaoyihao** [comment]
> 我也写不来 python 的错误解析
我抄了一个这个的
配置了还是不行。。
![5401623418115_ pic_hd](https://user-images.githubusercontent.com/52092094/121693760-ffac0e00-cafb-11eb-914a-3122d1a4c22a.jpg)

![5391623418024_ pic_hd](https://user-images.githubusercontent.com/52092094/121693547-d7241400-cafb-11eb-88e1-5b8108434b60.jpg)

**Comment by taotaoyihao** [comment]
在:help errorformat里面抄的
