### ISSUE TITLE
output missing in quickfix error message

### ISSUE THREAD

**Issue by Konfekt** [skywind3000/asyncrun.vim#232]
When running [langtool](https://github.com/Konfekt/vim-langtool/) with

```vim
command! -bang -nargs=* Make AsyncRun<bang> -auto=make -program=make <args>
```

output is missing in the error message:
The quickfix list opens and shows

```
/home/konfekt/test.txt|8 col 8 info| PASSIV_SAETZE[1]
```

instead of 

```
/home/konfekt/test.txt|8 col 8 info| PASSIV_SAETZE[1] : Passivsatz: Aktiv formulierte Sätze sprechen im Regelfall den Leser stärker an.
```

The whole error message is only shown after closing and reopening the quickfix list window.

**Comment by skywind3000** [comment]
check your errorformat

**Comment by Konfekt** [comment]
> The whole error message is only shown after closing and reopening the quickfix list window.

How could this be related to the error format? Without asyncrun the error messages show up fine.

**Comment by Konfekt** [comment]
I suspect the issue rather with asyncrun erroneously interpreting the colon `:` in the error message to filter out what follows it.

**Comment by tomtomjhj** [comment]
> The whole error message is only shown after closing and reopening the quickfix list window.

I'm experiencing the same issue (with `cargo`). Have you found a solution?

**Comment by Konfekt** [comment]
>  So I'm adding `-post=silent!\ cnewer` argument

This is a good workaround of the issue at hand; I circumvented it using https://github.com/mg979/tasks.vim

**Comment by skywind3000** [comment]
This seems to be caused by multi-line errors progressively adding into quickfix,  

try: adding a `-once` argument, it will ensure all output will be added to quickfix and matched at once:

    command! -bang -nargs=* Make AsyncRun<bang> -once -auto=make -program=make <args>

for more information, visit [here](https://github.com/skywind3000/asyncrun.vim/wiki/Command-Specification#quickfix-options)

**Comment by tomtomjhj** [comment]
Thanks, that worked too. So the issue was that multi-line output can't be properly recognized on-the-fly. 

Here's an idea: while running, act like `-raw` so that the user can see the intact output on-the-fly, and at the end, apply efm. Is this possible already or implementable?
