### ISSUE TITLE
go run hasn't stdout by -mode=async?

### ISSUE THREAD

**Issue by BYT0723** [skywind3000/asyncrun.vim#234]
AsyncRun go run main.go
![image](https://user-images.githubusercontent.com/59989961/148143371-347ad734-a5a1-427e-9778-a5d765110925.png)
AsyncRun -mode=term go run main.go
![image](https://user-images.githubusercontent.com/59989961/148143412-3382f3da-df29-41d9-a38a-750bd92f83ae.png)

**Comment by BYT0723** [comment]
Async will run normally when the buffer of go file is closing
![image](https://user-images.githubusercontent.com/59989961/148144968-d7250ebf-d931-44e8-98ee-6bb9410ffc42.png)
![image](https://user-images.githubusercontent.com/59989961/148145030-d4e6af17-99db-42ee-a6d3-835476271c57.png)

**Comment by skywind3000** [comment]
Your errorformat has been changed， try

    :AsyncRun -raw xxxx

**Comment by BYT0723** [comment]
Wooo, It's worked,Thank you
![image](https://user-images.githubusercontent.com/59989961/148146873-9782e367-ef5d-49c2-8443-f0f37503f320.png)
@skywind3000
