### ISSUE TITLE
7.4.1829 support broken?

### ISSUE THREAD

**Issue by kaihowl** [skywind3000/asyncrun.vim#242]
Install fresh compiled 7.4.1829 on Ubuntu 20.04. Use `d9cf2ae5d80821b8d0b1424392b28c18d7e032f6`. Vimrc is minimalistic:

```
set nocompatible
call plug#begin()
Plug 'skywind3000/asyncrun.vim'
call plug#end()
```

When calling `:AsyncRun echo test` I get the following error:

```
Error detected while processing function asyncrun#run[150]..<SNR>9_run[186]..<SNR>9_AsyncRun_Job_Start:
line  108:
E729: using Funcref as a String
E475: Invalid argument: exit_cb
ERROR: Background job start failed 'echo test'
```

**Comment by skywind3000** [comment]
I will check this later

**Comment by skywind3000** [comment]
fixed in https://github.com/skywind3000/asyncrun.vim/releases/tag/2.9.10

**Comment by kaihowl** [comment]
Confirmed working.
