### ISSUE TITLE
Quickfix window not opening automatically

### ISSUE THREAD

**Issue by pmurray17** [skywind3000/asyncrun.vim#244]
After updating asyncrun the quickfix window is not opening automatically when containing text.
vim 8.2 - patches 1-3423
asyncrun:2.9.11

augroup vimrc
 autocmd!
 autocmd QuickFixCmdPost * botright copen 8 
 autocmd QuickFixCmdPost make call AirlineRefresh
 "Close window if open when AsyncRun starts
 autocmd User AsyncRunStart call asyncrun#quickfix_toggle(8, 0)
 autocmd User AsyncRunStart AirlineRefresh
augroup END

command! -bang -nargs=* -complete=file Make AsyncRun! -strip -silent -program=make @ -s -f makefile.42r %:r.42m

**Comment by skywind3000** [comment]
use this:

    let g:asyncrun_open = 8

**Comment by pmurray17** [comment]
Thanks, already tried it to no effect.
I have moved back a version for now to get some work done and quickfix window opening as expected.

**Comment by skywind3000** [comment]
can you try to disable the latest qfid feature by:

    let g:asyncrun_qfid = 0

**Comment by pmurray17** [comment]
Hi,

Yes that has worked for me, shows up the errors in the quickfix window.
