### ISSUE TITLE
Can I map a key to copen then AsyncRun xxx?

### ISSUE THREAD

**Issue by sangshuduo** [skywind3000/asyncrun.vim#255]
sorry if the question is stupid

**Comment by skywind3000** [comment]
:noremap <f12> :copen | AsyncRun xxx <cr>

??

**Comment by sangshuduo** [comment]
this way does not work as I expected. copen and asyncrun do not run seamlessly. 
But I found the following works as what I expected (BTW, I am using neovim):

add two lines in lua/custom/init.lua

vim.cmd "let g:asyncrun_open = 6"
vim.cmd "noremap <F7> :AsyncRun make <cr>"

**Comment by skywind3000** [comment]
great
