### ISSUE TITLE
Avoiding too many jobs at once

### ISSUE THREAD

**Issue by kurko** [skywind3000/asyncrun.vim#26]
I'm working on this plugin where it calls another program asynchronously on every hit of a keyboard key. However, for obvious reasons, I'm getting `ERROR: background job is still running`.

I see two solutions

1. Not asyncrun.vim related: how to add a delay between key hit (still ongoing research, probably I'll have to check timestamps etc)
2. asyncrun.vim related: trying to do an `AsyncStop!` before every `AsyncStart!`, that way when the keys stop being pressed quickly, the last `AsyncStart!` will continue just fine (drawback is that the external program will probably be executed many times afaik).

On the solution 2, I'm trying this:

```vimscript
function! StopCommunications()
  exec ":AsyncStop!"
endfunction

function! StartCommunications()
  exec ":AsyncStop!"
  exec ":AsyncRun! my_program"
  " ...
endfunction

augroup MyPlugin
  autocmd!

  autocmd User AsyncRunPre :call StopCommunications()
  autocmd CursorMoved  * :call StartCommunications()
augroup END
```

Even with the `AsyncStop!` being called, I still get `ERROR: background job is still running`, which leads me to believe that I don't know how `AsyncStop!` works.

**Comment by skywind3000** [comment]
Job won't be killed by AsyncStop!, it just send a signal, process will be actually killed later.

There is a global variable named "g:asyncrun_status" which can indicate the status:
 'running', 'success' or 'failure'

You can check if there is a job still running by checking it , will it help ?

If you just need start a background process and don't care its output, you can just 

```VimL
call system("my command &")
```

as well. Will this help ?

**Comment by kurko** [comment]
I think `g:asyncrun_status` would be perfect for me. So what I did is:

```vimscript
let g:keyPressDelay = 2000
let g:JimmyKeyPressTimer = 0

function! JimmyStartCommunications(timer)
  exec ":AsyncRun! my-program"
endfunction

function! EntryPoint(input_string)
  " Basically I will start a timer for 2s. If I press a key in the mean time,
  " I kill the timer. I didn't know Vim 8 had this feature.
  call timer_stop(g:keyPressTimer)
  let g:keyPressTimer = timer_start(g:keyPressDelay, "StartCommunications")
endfunction

augroup Jimmy
  autocmd!
  autocmd CursorMoved  * :call EntryPoint("string")
augroup END
```

I believe the `g:asyncrun_status` should still be used because there's no way to know if the external program will take more than 2s.

Thanks a lot for the help.
