### ISSUE TITLE
should be able to use "%" like all other normal vim commands.

### ISSUE THREAD

**Issue by leoatchina** [skywind3000/asyncrun.vim#264]
After updated to the latest `Asyncrun.vim`, I found it would cause error when I use `%` as current file,  so I have to update my config, you can see my commit here and the screenshot after 
 https://github.com/leoatchina/leovim/commit/3fe350eb4f4bc9a8e6995bf6f47d0bff39a1a0b2#diff-619016acddd84d635046317ed3b5175f1f5b03994134bdff9ee336ae838d0668L88
![image](https://user-images.githubusercontent.com/4470821/199631353-7523d58f-3584-4f2e-86d9-23d04a5901dc.png)

In other way, if I want to handly type in `:AsyncRun` commands to run current file, it is more time costing to type in `VIM_FILEPATH` than `%`

**Comment by wookayin** [comment]
Which version were you using previously? I think the `$(VIM_FILEPATH)` hassles have been there for a while, like MANY years.

https://github.com/skywind3000/asyncrun.vim/wiki/FAQ#macro--is-expanded-incorrectly-on-windows-if-the-filename-contains-spaces-

I'm supportive of this -- we should be able to use "%" like all other normal vim commands.

**Comment by skywind3000** [comment]
fixed:
https://github.com/skywind3000/asyncrun.vim/releases/tag/2.10.9

**Comment by leoatchina** [comment]
fixed, thank you !

**Comment by wookayin** [comment]
Hmm I wrote #261, sorry, but I didn't know `file` and `shellcmd` have different impacts on "%". Actually relying on the "file" completion behavior to deal with `%` is a weird hack. Let me try a better alternative that would also make `%` useful.
