### ISSUE TITLE
Any way to auto-scroll when using term with no focus?

### ISSUE THREAD

**Issue by skamsie** [skywind3000/asyncrun.vim#268]
I would like to have auto-scroll similar to the quickfix window when using `-mode=term` and `-focus=0` similar to how it is for the default (quickfix window). Is there any way to achieve this?

For example with this command there is no auto-scroll `:AsyncRun -mode=term -pos=bottom -focus=0 -scroll=1 -rows=20 ruby %`

**Comment by skywind3000** [comment]
fixed in:

https://github.com/skywind3000/asyncrun.vim/releases/tag/2.11.10

**Comment by skywind3000** [comment]
please update again, I have enabled `reuse` by default for split terminal buffers:

https://github.com/skywind3000/asyncrun.vim/releases/tag/2.11.12

**Comment by skywind3000** [comment]
polish it again, a terminal window can only be reused if it is created by asyncrun.
prevent side-effect to other terminal related plugins.

**Comment by skamsie** [comment]
If you don't mind adding, now the autoscroll can't be disabled when `mode=term` and `-focus=0` (basically passing `scroll=0` is ignored). It's not something I would personally use, but for consistency's sake it would be nice to have this parameter work as it does for the quickfix window.

**Comment by skywind3000** [comment]
updated
