### ISSUE TITLE
Problem getting asyncrun to use same $PATH as vim

### ISSUE THREAD

**Issue by blakesweeney** [skywind3000/asyncrun.vim#28]
The asyncrun command does not use the same `$PATH` as vim. In my shell:

```sh
$ echo $PATH
/Users/bsweeney/ebi/rnacentral-web/.direnv/python-2.7.10/bin:...
```

Then in vim:

```vim
:echo $PATH
```

produces:

```
/Users/bsweeney/ebi/rnacentral-web/.direnv/python-2.7.10/bin:..
```

but:

```vim
:AsyncRun echo "$PATH"
```

produces

```
/usr/local/opt/coreutils/libexec/gnubin:..
```

I suspect this is because I use [direnv](https://github.com/direnv/direnv) to set my path depending upon what directory I am in. I'm not sure how to either get the shell asyncrun uses to respect this, or how to pass PATH to the command. Is it possible?

**Comment by skywind3000** [comment]
AsyncRun has nothing to do with $PATH, maybe it has been reset by bash or sh (see your &shell config), &shell is used by AsyncRun to launch the command.

**Comment by blakesweeney** [comment]
Thanks, I'll play around with &shell a bit and see if I can fix it. Closing since this really isn't an issue with  your plugin.
