### ISSUE TITLE
Mistake in readme.

### ISSUE THREAD

**Issue by mclehman** [skywind3000/asyncrun.vim#29]
'%>' should be '%<' in "Macro '%' stands for filename and '%>' represents filename without extension."

I forked and was about to submit a pull request, but changing one line seems to have resulted in 188 lines of whitespace changes.

**Comment by skywind3000** [comment]
That's alright, you can change 188 lines, maybe a `\r\n` problem

**Comment by skywind3000** [comment]
thanks, fixed.
