### ISSUE TITLE
is there any method like asyncrun#quickfix_toggle?

### ISSUE THREAD

**Issue by 0BananaBig0** [skywind3000/asyncrun.vim#291]
let g:asyncrun_mode = 'term'
Now, I set the mode to be a term. I found that the method quickfix_toggle not works as what I want. Is there any method that help me to toggle a term like a quickfix?

**Comment by 0BananaBig0** [comment]
function! ToggleTerminal(height)
    " Step 1: Check if there is a terminal window visible in the current tab
    let l:terminal_shown = 0
    let l:terminal_buffer = -1
  
    " Loop through all windows to check for a terminal
    for l:win in range(1, winnr('$'))
      if getbufvar(winbufnr(l:win), '&buftype') ==# 'terminal'
        " A terminal window is found, set the flag and get the buffer number
        let l:terminal_shown = 1
        let l:terminal_buffer = winbufnr(l:win)
        " Switch to the terminal window to hide it
        execute l:win . "wincmd w"
        " Hide the terminal
        hide
        break
      endif
    endfor
  
    " Step 2: If no terminal window is visible, check for a hidden terminal buffer
    if l:terminal_shown == 0
      " Get the list of all buffers and find the latest terminal buffer
      let l:latest_terminal = -1
      for l:buf in reverse(range(1, bufnr('$')))
        if getbufvar(l:buf, '&buftype') ==# 'terminal'
          let l:latest_terminal = l:buf
          break
        endif
      endfor
  
      " Step 3: Open the latest terminal buffer if found, or open a new terminal
      if l:latest_terminal != -1
        " Open the terminal buffer in a new split at the bottom with the specified height
        execute 'belowright ' . a:height . ' split | b ' . l:latest_terminal
      else
        " If no terminal buffer exists, open a new terminal at the bottom with the specified height
        execute 'belowright ' . a:height . ' terminal'
      endif
    endif
  endfunction
  let g:asyncrun_bell = 1
  let g:asyncrun_save = 1
  let g:asyncrun_mode = 'terminal'
  nnoremap <silent><F8> :silent call ToggleTerminal(6)<CR>
  nnoremap <Space><F8> :AsyncRun! -strip -focus=0 -rows=6 -hidden=1<Space>
this works.

**Comment by 0BananaBig0** [comment]
function! ToggleTerminal(height)
    " Step 1: Check if there is a terminal window visible in the current tab
    let l:terminal_shown = 0
    let l:terminal_buffer = -1

    " Loop through all windows to check for a terminal
    for l:win in range(1, winnr('$'))
      if getbufvar(winbufnr(l:win), '&buftype') ==# 'terminal'
        " A terminal window is found, set the flag and get the buffer number
        let l:terminal_shown = 1
        let l:terminal_buffer = winbufnr(l:win)
        " Switch to the terminal window to hide it
        exec l:win . "wincmd w"
        " Hide the terminal
        hide
        break
      endif
    endfor

    " Step 2: If no terminal window is visible, check for a hidden terminal buffer
    if l:terminal_shown == 0
      " Get the list of all buffers and find the latest terminal buffer
      let l:latest_terminal = -1
      for l:buf in reverse(range(1, bufnr('$')))
        if getbufvar(l:buf, '&buftype') ==# 'terminal'
          let l:latest_terminal = l:buf
          break
        endif
      endfor

      " Step 3: Open the latest terminal buffer if found, or open a new terminal
      if l:latest_terminal != -1
        " Open the terminal buffer in a new split at the bottom with the specified height
        exec 'belowright ' . a:height . ' split | b ' . l:latest_terminal
      else
        " If no terminal buffer exists, open a new terminal at the bottom with the specified height
        exec 'belowright ' . ' terminal'
        call feedkeys("\<C-\>\<C-n>", "n")
        exec 'resize ' . a:height
      endif
    endif
  endfunction
  let g:asyncrun_bell = 1
  let g:asyncrun_save = 1
  let g:asyncrun_mode = 'terminal'
  nnoremap <silent><F8> :silent call ToggleTerminal(6)<CR>
  nnoremap <Space><F8> :AsyncRun! -strip -focus=0 -rows=6 -hidden=1<Space>
this works.

**Comment by skywind3000** [comment]
nice!
any way, you can also try 

```vim
:AsyncRun -mode=term -pos=TAB  ls -la
```

it will open a new tab page in the left of current tab, and when it closed, you will return to your previous tab page.

**Comment by 0BananaBig0** [comment]
> nice! any way, you can also try
> 
> ```viml
> :AsyncRun -mode=term -pos=TAB  ls -la
> ```
> 
> it will open a new tab page in the left of current tab, and when it closed, you will return to your previous tab page.

Got it,thanks.
