### ISSUE TITLE
Output not captured in Quickfix for python scripts

### ISSUE THREAD

**Issue by heitzmann** [skywind3000/asyncrun.vim#30]
Output of python scripts is not displayed in the Quickfix window.

I have the following in a `test.py` file:
```python
# File: test.py
print('Hello world!')
```

If I run `:AsyncRun python test.py` the Quickfix window does not display the message. It simply shows:
```
|| [python test.py]
|| 
|| [Finished in 0 seconds]
```

But if I execute `:AsyncRun python -c 'print("Hello world!")'` I correctly get:
```
|| [python -c 'print("Hello world!")']
|| Hello world!
|| 
|| [Finished in 0 seconds]
```

In bash, for example, it works fine. If I have a file `test.sh` with:
```bash
# File: test.sh
echo 'Hello world!'
```
and execute `:AsyncRun bash test.sh` I get:
```
|| [bash test.sh]
|| Hello world!
|| 
|| [Finished in 0 seconds]
```

What am I missing here? Is there a problem with python output?

**Comment by skywind3000** [comment]
I can't reproduce your issue on both Windows and Linux.

Can you provide some details about:
1. version of vim
2. version of asyncrun
3. what os are you working on ?

**Comment by heitzmann** [comment]
Sure, I forgot to mention that! I'm on Linux (4.9) and I'm using NeoVim 0.1.7, not vim, with the latest AsyncRun commit (1467e58).

**Comment by skywind3000** [comment]
It seems that output from stdout has been dropped by neovim 0.1.7 if the child process exits too immediately. NeoVim 0.1.7 may buffer the output from child process, but before passing to AsyncRun, it found job finished and simply discarded the buffering data.

But it seems okay in my `NVIM v0.2.0-211-g9009c20`, I could't reproduce your problem in nvim 0.2.0 either, maybe the issue has been fixed already ??

**Comment by heitzmann** [comment]
Thanks for the response. I get the same problem in neovim 0.2.
I've run many tests and it actually seems to be some incompatibility with [vim-polyglot](https://github.com/sheerun/vim-polyglot) or some of its language packs.

The problem happens when the 1st buffer I load in neovim (or even vim 8.0.314 – I tested both) is a python file.
I've also seen this issue with latex files (compilation output is mostly missing, except for errors).

In any case, removing vim-polyglot solved the issue for now. Since the problem could be with vim-polyglot, feel free to close this issue.

**Comment by skywind3000** [comment]
Maybe global value of errorformat has been modified by vim-polyglot ?
errorformat can trim messages in quickfix (eg, u can configurate your errorformat to display errors only, not warnings or others).

Is it possible that somewhere in vim-polyglot changes your global `errorformat` ? If so , you can check the difference of `errorformat` when you are opening a .py file and a .sh file.

**Comment by heitzmann** [comment]
You are right! The python language pack from vim-polyglot modifies `errorformat`. In fact, by searching in the repository I imagine many other languages would suffer from the same problem...

**Comment by skywind3000** [comment]
Since you find the problem, you can set it back now and this issue could be closed now.

**Comment by teleyinex** [comment]
Thanks to this I solved this issue for me as well :-) THANKS

**Comment by aemonge** [comment]
Is there a way to set the errorformat to a local QuickFix window of the AsyncRun, to support poliglot and more?
