### ISSUE TITLE
Usage with a debugger

### ISSUE THREAD

**Issue by joeltaylor** [skywind3000/asyncrun.vim#32]
Is it possible to add a debugger, run a test async, and then pop into a debug session when the debugger is reached? 

Right now, the only way I can get this to work is to set the mode to either `make` or `:!`. When I run with async mode, it'll act like it wants to pop into a debug session, but will continue past it.

**Comment by skywind3000** [comment]
I don't really get what a "debug session" means in vim ?

Could you provide some steps in detail ? 
How do you switch into your `debug session` by using `make` or `!` ?

**Comment by joeltaylor** [comment]
Of course, apologies for the vagueness! 

When I write Ruby, I use a debugger called [byebug](https://github.com/deivid-rodriguez/byebug) that allows me to add a breakpoint in my code. When I run the tests via `make` or `!`, a REPL style session will start when the test comes across the breakpoint allowing me to poke around from the command line. Here's a gif demonstrating running the specs with `make` and then async:
![test](https://cloud.githubusercontent.com/assets/6965062/22752059/ee5e08de-edeb-11e6-8c26-764bd72080ad.gif)

It may not be possible to do this when using Async mode, mostly curious.

**Comment by jmgarnier** [comment]
I use byebug every day with tmux and when I need to debug, I just move to the pane and run manually the test. @joeltaylor What would be the value of having this "debugging" feature inside `asyncrun` ? It could also work with iterm tab.

It's quite a powerful plugin as it is and maybe @skywind3000 does not have much free time to spend on adding more features like this one.

**Comment by joeltaylor** [comment]
@jmgarnier it's just my preferred workflow. This wasn't intended to be a feature request and was just an inquiry in the event I was missing something.

**Comment by skywind3000** [comment]
Sorry, AsyncRun cannot take any input from stdin, stdin has been closed before launching the command.
Anything trying to be read from stdin will get a EOF.

QuickFix windows is not an interactive shell, if the child process is expecting data from stdin, it will hang until `:AsyncStop`,  so the stdin has been closed to avoid this.

Debug in vim need a real shell.

**Comment by joeltaylor** [comment]
That makes sense. Thanks for the explanation!
