### ISSUE TITLE
ERROR: invalid config in &shell and &shellcmdflag, &shell must be an executable.

### ISSUE THREAD

**Issue by masukomi** [skywind3000/asyncrun.vim#33]
tried it launching from fish and bash and after running chsh to make it bash after having tried in fish. always same result.

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  3 2017 16:49:50)
MacOS X (unix) version
Included patches: 1-297

**Comment by skywind3000** [comment]
What is the value of &shell and &shellcmdflag in your config ??

```VimL
:echo &shell
```

```VimL
:echo &shellcmdflag
```

AsyncRun uses &shell to execute the command, so the correct form is:

```VimL
:set shell=bash
:set shellcmdflag=-c
```

The incorrect for is:

```VimL
:set shell=bash\ -c
```

**Comment by masukomi** [comment]
`:echo &shell` emits `/bin/bash/ -i` 

`:echo &shellcmdflag` emits `-ic`

i have no idea where those came from, but things like `:! ls` work just fine. 

changing it to be as you suggested works fine. I'm not sure if this should be closed or not because it's not clear to me that what i had should have been producing an error.

**Comment by skywind3000** [comment]
Checking the documentation in `:h shellcmdflag` and `:h shell` carefully,
I believe that `shell` is supposed to represent the shell executable and `shellcmdflag` is the parameters which will be passed to `shell` .

But a lot of plugins confuse them.
