### ISSUE TITLE
Is there a way to stream the output?

### ISSUE THREAD

**Issue by nkmathew** [skywind3000/asyncrun.vim#4]
E.g. when make is running. Getting the output in 'realtime' instead of running `:copen` every time to update the quickfix window manually?

**Comment by skywind3000** [comment]
you can leave quick fix window there without close it each time or write a ToggleQuickfix() function and bind to a key ?

**Comment by nkmathew** [comment]
Yeah, looks like the best alternative, in addition to these autocommands:

```vim
autocmd BufReadPost quickfix nnoremap <buffer> r :copen<CR>
autocmd BufReadPost quickfix nnoremap <buffer> R :copen<CR>G

```

**Comment by skywind3000** [comment]
There is a function to toggle quickfix window in the latest version of asyncrun.vim:

[best-practice-with-quickfix-window](https://github.com/skywind3000/asyncrun.vim#best-practice-with-quickfix-window)
