### ISSUE TITLE
Problem with feross/standard

### ISSUE THREAD

**Issue by zhmars** [skywind3000/asyncrun.vim#40]
Hi, it seems not work  well with [feross/standard](https://github.com/feross/standard).

But use the command  ':!standard test.js'  is fine.

Please forgive my poor English :)

![standard](https://cloud.githubusercontent.com/assets/18466397/23508089/013f1302-ff8b-11e6-939a-980811fcd9ec.png)

**Comment by skywind3000** [comment]
那是因为 AsyncRun 用到了 caddexpr 命令给 quickfix 增加内容，而 caddexpr不支持 local errorformat只支持 global errorformat，你可以试着设置一下 global errorformat，支持这种多行的错误输出。

**Comment by zhmars** [comment]
你好，我补充下，这里的 test.js 文件内容是空的哦，执行 ':!standard test.js‘ 的输出结果也是空的。

global errorformat 需要设置成什么呢？

![123](https://cloud.githubusercontent.com/assets/18466397/23548702/be1e2fc2-0043-11e7-84d5-a9db399e5cb7.png)

**Comment by skywind3000** [comment]
哦，你的意思是运行错误了？
那检查一下环境变量是否一致，AsyncRun调用 job_start的时候是使用 cmd.exe, bash 来启动命令行的，你能否 asyncrun 一个 bat文件，bat文件里面输出下环境变量，或者运行

```VimL
:AsyncRun set
```

查看下环境变量，检查一下环境变量是否正确？

**Comment by zhmars** [comment]
恩恩，在 cmd 直接执行没报错，用 asyncrun 调用时就出现了，而且用的两台机子都有这问题，你那边能重现么？

刚检查了环境变量，cmd 直接运行 'set' 跟  执行 ':AsyncRun set' ，结果除了 vim 自身的变量和我自己定义的变量外，其它一样的。

**Comment by skywind3000** [comment]
发现一个：“unknow stdin file type”

因为 stdin 被 AsyncRun 关闭了，因为有一些需要交互的程序会依赖标准输入读取用户的键盘输入。
而 AsyncRun 使用 job 系统来启动程序并把结果输出到 QuickFix 的过程中是没办法接受输入的。
所以 AsyncRun 启动程序的时候把  stdin 关闭了，如果不这么做，那么一些需要从标准输入读取数据
的工具就会一直死锁在那里无法结束。

你看看是否有参数可以忽略标准输入。

**Comment by zhmars** [comment]
刚查了下选项，没有忽略标准输入，指定文件从标准输入读取的参数倒是有  :(

**Comment by zhmars** [comment]
你好，问题暂时解决了。刚看 asyncrun 的文档，发现还有 mode 参数，我试了下面两条命令，结果都正常，暂时用第一个命令代替

> :AsyncRun  -mode=1 standard test.js
> :AsyncRun  -mode=2 standard test.js
