### ISSUE TITLE
How to stay in current window after asyncrun finishes?

### ISSUE THREAD

**Issue by noscripter** [skywind3000/asyncrun.vim#41]
I remember there was this function to customize whether to jump to the quickfix window when asyncrun finishes, but I can't find it in the document now, wonder if there is still some way to customize this behavior?

Put it simple, I just want the quickfix to be open but remain my current editing window instead of jumping to the quickfix window.

**Comment by skywind3000** [comment]
It has been discussed in: https://github.com/skywind3000/asyncrun.vim/wiki/Quickfix-Best-Practice
