### ISSUE TITLE
Can this plugin run functions defined in .vimrc execute asynchronously?

### ISSUE THREAD

**Issue by alekcacko** [skywind3000/asyncrun.vim#43]
For example, I have this function:

func! CompileCppAndRun()
        "silent w
        "silent make
        execute "copen"
        if (line('$') == 1 && getline(1) == '')
            silent execute ":cclose"
            let cexec = "".  "%:p:r "
          silent execute "!clear"
          silent execute "!" . "xterm " . "-e " . "cb_console_runner " . cexec
        endif

endfunc

This is a function that compiles c++ program, executes if compiled or opens quickfix if there are compile errors.

So, can AsyncRun call this function?

**Comment by skywind3000** [comment]
No, job_start in vim can only run external process.
You can implement it in a .sh script and launch it by AsyncRun.

**Comment by alekcacko** [comment]
Oh, thank you, then I think I can close the issue.
