### ISSUE TITLE
(Question) Format asyncrun's output

### ISSUE THREAD

**Issue by jonasstoetzel** [skywind3000/asyncrun.vim#45]
When I'm running a python script, all output lines in the quickfix window are prefaced with `||`, i.e.

    || line 1
    || line 2

Can I somehow get rid of these lines? I searched the FAQ but could not find a solution.
Thanks in advance!

**Comment by skywind3000** [comment]
AsyncRun uses `:caddexpr` command to insert text into quickfix window to benefit from vim's buitin error matching system.
And the "||" was added by caddexpr，AsyncRun has nothing to do with that.
