### ISSUE TITLE
能否增加对 ex command ranges 的支持

### ISSUE THREAD

**Issue by zbinlin** [skywind3000/asyncrun.vim#46]
如果可以直接使用 `:%AsyncRun` 来运行当前 buffer 区里的命令，这样对于需要修改重复运行的命令的方便多了，毕竟在 vim 里比在 shell 里容易编辑命令 :)

**Comment by skywind3000** [comment]
我不太清楚你的需求，buffer里面的命令是python命令？shell命令？bash/sh/zsh ？perl？以什么确定？文件头一行？还是扩展名？运行buffer命令的目录是？当前目录？

这个很个人化的东西，你可以自己实现这条命令，把缓存里的东西保存到临时文件里面，然后调用AsyncRun去执行它，因为即便我做我也得这么做的。

**Comment by zbinlin** [comment]
就是普通的 shell 命令，比如我需要使用 curl 来测试一个 API，如果这条命令太长，直接在 shell 里修改起来比较麻烦。如果可以这样：直接打开 vim，然后在 vim 里输入这条命令，然后直接使用 `:%AsyncRun` 来运行这条命令，这样如果需要修改命令，然后运行，直接在 vim 里编辑比 shell 里方便多了。

**Comment by zbinlin** [comment]
这个功能有点像 `:AsyncRun! man -S 3:2:1 <cword>`，只是把 `<cword>` 换成整个 buffer 的内容

**Comment by zbinlin** [comment]
已找到类似的 plugin： https://github.com/JarrodCTaylor/vim-shell-executor

**Comment by skywind3000** [comment]
嗯，你看的这个插件并不能异步执行，它要把你整个vim停下来去执行东西去，完了你才能继续。

**Comment by zbinlin** [comment]
所以如果你这边可以实现就最好啦 :)

这里还有一个类似：https://github.com/krisajenkins/vim-pipe
