### ISSUE TITLE
quick fix问题

### ISSUE THREAD

**Issue by lemon0910** [skywind3000/asyncrun.vim#47]
插件安装成功，使用gcc可以生成二进制文件，但是没有quick fix窗口展示，请问这是什么问题？

**Comment by skywind3000** [comment]
你提个issue连重现步奏，怎么操作都不给，我怎么帮你看呢？

1. 你 copen打开了quickfix了没有？
2. 你的 errorformat是不是被改过？

errorformat 控制 quickfix 里的错误匹配和信息过滤。
https://github.com/skywind3000/asyncrun.vim/issues/37

**Comment by lemon0910** [comment]
恩，不好意思，copen没开
