### ISSUE TITLE
[suggestion] more friendly readme about copen

### ISSUE THREAD

**Issue by ZSaberLv0** [skywind3000/asyncrun.vim#48]
new to this plugin, nowhere to find why i have no quickfix popup after running the command, after a long search, finally found that i should call `copen` manually to see the result (usually i prefer quickfix window to be closed)

suggestion:
* add an option to open quickfix automatically after command finish, and, make it default to true
* add description about `copen` manually, in plugin's readme
* or, have this setting as default:

    ```
    let g:asyncrun_exit='echo "AsyncRun " . g:asyncrun_status . "(" . g:asyncrun_code'
        \ . ' . "), use `:copen` to see the result"'
    ```

**Comment by remyabel** [comment]
This is covered by the [FAQ](https://github.com/skywind3000/asyncrun.vim/wiki/Quickfix-Best-Practice).

**Comment by ZSaberLv0** [comment]
i mean it's better to make default config more friendly for new users

**Comment by skywind3000** [comment]
Some people like to keep quickfix window hidden all the time, except there are errors.
While others like to get quickfix window open after vim starts, to keep window layout.

**Comment by skywind3000** [comment]
Show quickfix window by default is convenience for you , not the others.
