### ISSUE TITLE
save only saves current file

### ISSUE THREAD

**Issue by marblepebble** [skywind3000/asyncrun.vim#51]
I've just switched to this from using :make and waiting. I used to have the autowrite option, so when I invoked make it would save any changed buffers. Using AsyncRun -save only saves the current buffer.
This seems easy enough to fix - I've changed the 'silent update' to 'silent wall' locally.

**Comment by skywind3000** [comment]
`update` will save the file only if it has been modified.

`wall` will save the file every time.

**Comment by marblepebble** [comment]
No, http://vimdoc.sourceforge.net/htmldoc/editing.html#buffer-write says that wall writes only changed buffers - ie. it's more like update-all than write-all.

**Comment by skywind3000** [comment]
For compatibility sake,
I have published a new release, and add an option (-save=2) to save all modified buffers.

**Comment by marblepebble** [comment]
Fantastic, thank you!
