### ISSUE TITLE
No realtime output when asyncrun non-shell-scripts

### ISSUE THREAD

**Issue by colben** [skywind3000/asyncrun.vim#52]
#### Environment
OS: Archlinux
vim-version: 8
#### Script file /home/colben/a.sh
```
#!/bin/bash
while :; do
    echo 'aaaaaaaa'
    sleep 1
done
```
#### Script file /home/colben/a.py
```
#!/usr/bin/python2
from time import sleep

def main():
    print 'bbbbbbbb'
    sleep(1)
    print 'bbbbbbbb'
    sleep(1)
    print 'bbbbbbbb'
    sleep(1)
    print 'bbbbbbbb'
    sleep(1)

if '__main__' == __name__:
    main()
```
#### Run vim in a new terminal
- open qw and run ":AsyncRun /home/colben/a.sh", it showed 'aaaaaaaa' every second
- open qw and run ":AsyncRun /home/colben/a.py", it printed nothing when 'a.py' wasing running, and showed all four lines 'bbbbbbbb' one time after 'a.py' stopped
#### Question
- why python scripts can not ouput realtime

**Comment by skywind3000** [comment]
```Python
#!/usr/bin/python2
from time import sleep
import sys

def main():
    print 'bbbbbbbb'
    sleep(1)
    print 'bbbbbbbb'
    sys.stdout.flush()
    sleep(1)
    print 'bbbbbbbb'
    sys.stdout.flush()
    sleep(1)
    print 'bbbbbbbb'
    sys.stdout.flush()
    sleep(1)

if '__main__' == __name__:
    main()
```

Stdout will not flush when running as a pipe , You should flush stdout manually

**Comment by colben** [comment]
Thanks！
Without flushing /dev/stdout, a python script can also print realtime when it's running in a shell terminal, why ?

**Comment by skywind3000** [comment]
when stdout is a tty it will flush after every "\n"
when stdout is a pipe it will not flush until process exits.

you can force flush by:

```
python  -u script.py
```

**Comment by colben** [comment]
Thank you!!!!

**Comment by colben** [comment]
Another qunestion: I wrote a py-script containing an interactive function "raw_input":
```
#!/usr/bin/python2

def main():
    print 'aaaaaaaa'
    sleep(1)
    input_string = raw_input('bbbbbbbb:')
    print 'aaaaaaaa'
    sleep(1)
    print 'aaaaaaaa'
    sleep(1)
    print 'aaaaaaaa'
    sleep(1)
    return

if '__main__' == __name__:
    main()
```
As I run :AsyncRun python2 -u %:p, qw showed error below directly without input prompt ...
```
|| [python2 -u /home/colben/a.py]
|| aaaaaaaa
|| bbbbbbbb:Traceback (most recent call last):
||   File "/home/colben/a.py", line 25, in <module>
||     main()
||   File "/home/colben/a.py", line 15, in main
||     input_string = raw_input('bbbbbbbb:')
|| EOFError: EOF when reading a line
|| [Finished in 1 seconds with code 1]
```
Can asyncrun.vim support input from /dev/stdin ?

**Comment by skywind3000** [comment]
Interacting with user inputs requires a real terminal and quickfix window can't read any user input.
Job will hang there while waiting data from raw_input until you call AsyncStop.
To prevent this, STDIN was closed before executing child process.
And any child process trying to read from stdin will get an EOF

**Comment by colben** [comment]
Thanks for your excelent answer!

**Comment by skywind3000** [comment]
for python, you can have:

```VimL
let $PYTHONUNBUFFERED=1
```

in your `.vimrc`
