### ISSUE TITLE
Can't run AsynRun using in cygwin shell

### ISSUE THREAD

**Issue by continnd** [skywind3000/asyncrun.vim#53]
I'm able to use the zsh.exe bundled in cygwin for pretty much anything when using the Windows version of vim, but every command exits with result code 1. My settings:

  set shell=c:\\cygwin64\\bin\\zsh.exe
  set shellcmdflag=--login\ -c
  set shellxquote=\"
  set shellslash

Even if I use ':AsyncRun ls' the command returns with result code 1 and prints nothing to the quickfix window.

**Comment by skywind3000** [comment]
No, asyncrun on gvim will only take the arguments as the commands of CMD.EXE.
As a replacement, you need run 'ls' like this:

```VimL
:AsyncRun c:\cygwin64\bin\zsh.exe --login -c "ls"
```

It works for me.

**Comment by continnd** [comment]
Alright, I've done that, but now I have an issue where quickfix will constantly steal my focus. Has anyone encountered this before?

**Comment by skywind3000** [comment]
No, I use gvim everyday and haven't seen that before.
that must be done by some evil plugins listening update autocmds from quickfix.

**Comment by continnd** [comment]
You were right. vim-qf was auto opening quickfix when every time there was an error, so I am going to have to disable that feature. Thanks for your help.
