### ISSUE TITLE
g:asyncrun_hook

### ISSUE THREAD

**Issue by ericmccarthy7** [skywind3000/asyncrun.vim#54]
Hi @skywind3000 

This is more of a question than an issue.

What is the purpose of g:asyncrun_hook?

It seems to only take place when the mode is set to >= 10 so I'm assuming it's something for debugging or you were just playing around with some stuff. 

Thanks!

**Comment by skywind3000** [comment]
for calling external background runner rather than job_start.

**Comment by ericmccarthy7** [comment]
ok thanks!
