### ISSUE TITLE
What is the async_state used for?

### ISSUE THREAD

**Issue by ericmccarthy7** [skywind3000/asyncrun.vim#56]
@skywind3000 

Sorry to bug you again, having trouble figuring out what async_state is used for. Seems like it's using bitwise operations, and it somehow prevents new jobs starting up. What does it do?

This is a really cool project and I'm looking to maybe contribute some features (if you're open to it).

**Comment by skywind3000** [comment]
close_cb, exit_cb in job system may become misorder in vim 8.0.
async_state is used to guarantee both of them are invoked.

**Comment by ericmccarthy7** [comment]
makes sense thanks
