### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by tdi** [skywind3000/asyncrun.vim#58]
I would like to use Asyncrun to run the script I am currently developing. e.g. `:AsyncRun %` . This however does not display standard output from the script. I am guessing it is not matched by errorformat. Is there a way to display whatever?

**Comment by skywind3000** [comment]
Would you provide some detail ? like screen capture ?
Expected output ? 
Actual output ?

**Comment by skywind3000** [comment]
you can try the new option `-raw` in the latest version:

```VimL
:AsyncRun -raw ls -la /
```

**Comment by tdi** [comment]
This is great. Solved my problem thanks. Actually it was caused by polyglot plugin.

**Comment by skywind3000** [comment]
That is an old plugin which will definitely destroy the user experience in the future vim 8.0 plugins.

**Comment by tdi** [comment]
@skywind3000 what else do you suggest?

**Comment by skywind3000** [comment]
use individual language plugins directly. polyglot has 100+ packages intergrated, but I only need 3 language plugins for everyday usage.

**Comment by tdi** [comment]
@skywind3000 true that - I was lazy though :)
