### ISSUE TITLE
term flickers with missing -raw

### ISSUE THREAD

**Issue by davidnorthetal** [skywind3000/asyncrun.vim#61]
Hey there,

running a python script with AsyncRun and no -raw my term flickers whenever the QF window updates.

Any idea what might cause this?

Version is:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 16 2017 07:36:03)

And I'm using
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
as my term

Thanks for any responses

**Comment by davidnorthetal** [comment]
Somewhat resolved

**Comment by skywind3000** [comment]
how to solve that ??
