### ISSUE TITLE
It doesn't work with gvim on windows8.1

### ISSUE THREAD

**Issue by yehuohan** [skywind3000/asyncrun.vim#63]
It does no work when type command, for example :AsyncRun gcc -v, in the gvim on windows8.1.
Does it support gvim(8.0, x86) on  windows8.1?

**Comment by skywind3000** [comment]
你打开了 quickfix window 没有？所有输出都是再 quickfix window ，你要先打开才看得到啊：

:copen 8

**Comment by yehuohan** [comment]
呃。。没打开。。现在可以用了 👍

**Comment by sunqingyao** [comment]
@skywind3000 可以解释一下 `asyncrun#quickfix_toggle(8, 1)` 里各个参数的含义吗？[代码里的注释](https://github.com/skywind3000/asyncrun.vim/blob/9bf152734e9a60b20843c675a5e1a13acfcc97c5/plugin/asyncrun.vim#L1253)讲得不太清楚 😞

**Comment by skywind3000** [comment]
8 的意思是打开 quickfix 窗口，高度是8，
1 的意思是强制打开，
0 的意思是强制关闭，
不填写最后一个参数，只写8的意思是切换。
