### ISSUE TITLE
g:asyncrun_mode not having an effect

### ISSUE THREAD

**Issue by joeltaylor** [skywind3000/asyncrun.vim#65]
I noticed that asyncrun stopped using my settings for `g:asyncrun_mode`. For example, in my .vimrc I have the following setting that no longer changes the mode: `let asyncrun_mode=1` 

However, using `-mode` continues to work. I believe the issue was introduced [here](https://github.com/skywind3000/asyncrun.vim/commit/5e2f5c08c46652132d6adb13351d717ab0041829#diff-dc0777985a6de9a42b33c4787dbf0fb9L863).

I took a stab at restoring the global variable check in this PR https://github.com/skywind3000/asyncrun.vim/pull/64

**Comment by skywind3000** [comment]
yes you are right, would you please change two spaces into a tab in your revision please ? 
perhaps I should add a mode line.

**Comment by joeltaylor** [comment]
Whoops, sorry about that. Just updated the spaces to tabs.

**Comment by skywind3000** [comment]
thanks
