### ISSUE TITLE
quickfix窗口不实时更新输出结果

### ISSUE THREAD

**Issue by tianshaokui** [skywind3000/asyncrun.vim#66]
在用asyncrun运行python或者c/c++编译的二进制文件时候， 只要程序没有运行结束，不会输出结果；
但是运行shell脚本时候， 输出结果是实时更新到quickfix窗口。

**Comment by skywind3000** [comment]
我晕，基础知识啊，那是因为你自己没有调用 python 的 sys.stdout.flush 或者 C 的 fflush ，默认再非终端模式下，他们是直到进程退出才会 flush，否则所有输出都是缓存再内存里面的，这个缓存模式不管 C/C++ 还是 python 都可以修改，你自己查查。。。。。

**Comment by tianshaokui** [comment]
谢谢指导，的确太基础了。 以后多查查在说
