### ISSUE TITLE
how to make the quickfix auto disapper  after running the asyncrun ?

### ISSUE THREAD

**Issue by CuriousFu** [skywind3000/asyncrun.vim#67]
the quickfix window does't hide or disapper automaticly after i use it to compile my code,
 a lot thanks if anyone could teach me to set it .

**Comment by skywind3000** [comment]
```VimL
:close
```

**Comment by CuriousFu** [comment]
Thank you for help， i mean weather it would  autoaticly close by itself after you do not focus on the quickfix window or after a delay，just like  syntastic.vim  or ale ?

**Comment by skywind3000** [comment]
AsyncRun 不负责操作 quickfix 窗口，每个人有每个人的习惯，你可以按你自己的习惯写一些 quickfix 控制代码
