### ISSUE TITLE
`g:asyncrun_rootmarkers` option not work

### ISSUE THREAD

**Issue by zhmars** [skywind3000/asyncrun.vim#68]
maybe there are some spelling errors between  wiki and the code

https://github.com/skywind3000/asyncrun.vim/wiki/Project-Root#config-root-markers

https://github.com/skywind3000/asyncrun.vim/blob/master/plugin/asyncrun.vim#L940-L941

**Comment by skywind3000** [comment]
thanks, typo has been fixed. 
refresh the wiki page again.
