### ISSUE TITLE
我知道你是中国人或者你至少看得懂中文，那么我的问题来了

### ISSUE THREAD

**Issue by JasonQWJ** [skywind3000/asyncrun.vim#69]
- 我尝试定义了快捷键如下：
`nnoremap <Leader>gph :AsyncRun git push<cr>`

- quickfix窗口返回了以下信息：
```
  1 || [git push]
  2 || Permission denied (publickey).
  3 || fatal: Could not read from remote repository.
  4 ||
  5 || Please make sure you have the correct access rights
  6 || and the repository exists.
  7 || [Finished in 3 seconds with code 128]
```

如果我直接在 vim内使用`:!git push`则是正常的，提示输入密码并提交代码。
是不是因为输入密码这一步没办法用异步的方式运行？？

**Comment by skywind3000** [comment]
防止读取输入卡住任务，同时quickfix 窗口也无处接受输入，后台的标准输入被关闭了，任何读取输入的操作都返回失败，大部分人都会选择保存仓库密码，你要输入密码你就需要一个真的终端

**Comment by JasonQWJ** [comment]
@skywind3000 确实，我已经放弃这个方式了。
