### ISSUE TITLE
[Question]: Neovim support?

### ISSUE THREAD

**Issue by deathmaz** [skywind3000/asyncrun.vim#7]
Hi, thank you for the plugin.
Do you have any plans for neovim support?

**Comment by skywind3000** [comment]
I will look at it if I get time.

**Comment by skywind3000** [comment]
As your wish, here, I am glad to tell you the latest asyncrun supports NeoVim now,
here is the change log of latest asyncrun:

1. support NeoVim above 0.1.4
2. better command line parsing, support using &makeprg to replace ':make' now.
3. cooperate with vim-fugitive and get fugitive async now.

welcome to have a try.

**Comment by deathmaz** [comment]
Awesome, thank you very much for you work! 👍
