### ISSUE TITLE
add option to open quickfix window automatcially 

### ISSUE THREAD

**Issue by pandysong** [skywind3000/asyncrun.vim#71]
Is it possible to add an option to open the quickfix window automatically?

Basically I want to open the quickwindow automatically. 
I tried:

AsyncRun python my_python.script % <bar>  copen
AsyncRun python my_python.script % | copen

however AsyncRun get parameter "finaname.... <bar> copen" as parameter of my_python.script

**Comment by pandysong** [comment]
sorry This issue could be closed.

I found the solution

:AsyncRun .... \| copen

**Comment by skywind3000** [comment]
https://github.com/skywind3000/asyncrun.vim/wiki/Quickfix-Best-Practice

文档里明明有。

**Comment by pandysong** [comment]
Thanks.
