### ISSUE TITLE
If you do a :grep while a background job is running, quickfix output is intermixed

### ISSUE THREAD

**Issue by mgedmin** [skywind3000/asyncrun.vim#73]
### Steps to reproduce

1. Run a command that takes a while and produces output using the `:Make` alias
2. While that job is running, do a quick `:grep`

### What happens

- Make output is now appended to the quickfix list of grep results

### What I expect

- Make output is appended to the older quickfix list that I can return to by doing `:colder`

This should be possible to do on a sufficiently-recent version of Vim (>= v8.0.1023) by using the `setqflist()` function and specifying the right quickfix list ID.

**Comment by Craige** [comment]
Agreed. AsyncRun should not clobber the active quickfix list. This breaks a great many workflows, especially if you have AsyncRun do something on buffer write. Your QuickFix list will be clobbered on every write.

**Comment by mgedmin** [comment]
#82 is a duplicate of this.
