### ISSUE TITLE
Problems in neovim when asyncrun is running.

### ISSUE THREAD

**Issue by phcerdan** [skywind3000/asyncrun.vim#75]
When asyncrun is running, neovim is not working as expected. For example, deleting a line with `dd` is not working, or visual selection with `shift-v` is flickering.
To test, in neovim latest release: `0.2`
`:AsyncRun xclock` or any GUI. Or `AsyncRun! sleep 1000`

**Comment by skywind3000** [comment]
Thanks, it has been fixed in the latest release.
