### ISSUE TITLE
Cannot use visual selection when asyncrun is running

### ISSUE THREAD

**Issue by fievel** [skywind3000/asyncrun.vim#76]
Visual selection do not work (it keeps flickering) as expected when a command is run through AsyncRun (even if quickfix window is closed). 

Vim 8.0 on Windows with latest asyncrun.vim version.

**Comment by skywind3000** [comment]
Bugs in vim's timer.
You should update your gvim to 8.0.12xx

**Comment by fievel** [comment]
Updated to:

    ```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 24 2017 22:07:09)
MS-Windows 64-bit GUI version
Included patches: 1-1216
    ```

But the bug is still there !

**Comment by skywind3000** [comment]
I just couldn't reproduce the issue, both on Windows GVim and Linux Vim.

Is it possible that there is a plugin conflict ?

**Comment by jimbz** [comment]
@fievel I had the same issue and for me it was due to the errormarker plugin adding an autocmd on `QuickFixCmdPost`. Removing the plugin fixed the problem.

**Comment by skywind3000** [comment]
please update to the latest version, and there is a new option `asyncrun_skip` can be used to disable specific autocmds:

```VimL
let g:asyncrun_skip = 7
```

This will skip all the autocmds.

**Comment by fievel** [comment]
I have still problems with this setting so can you keep the bug open, I will try to find you more information, by deactivating others plugins and so on.

**Comment by skywind3000** [comment]
thanks

**Comment by fievel** [comment]
I confirm the problem is with errormarker and the new setting does nothing to help. I will try to find out if the problem is in your code or in the errormarker code.

**Comment by skywind3000** [comment]
thanks

**Comment by fievel** [comment]
I found the problem and propose you a correction which seem to work at least in my environment.

**Comment by fievel** [comment]
Thanks for merging my correction. The bug can now be fixed.
