### ISSUE TITLE
Provide compatible :Make command

### ISSUE THREAD

**Issue by mcepl** [skywind3000/asyncrun.vim#8]
See https://github.com/tpope/vim-fugitive/issues/847#issuecomment-253815852

**Comment by skywind3000** [comment]
sure, I will look into it asap

**Comment by skywind3000** [comment]
I am glad to tell you, the latest `asyncrun.vim` can cooperate with fugitive now and get `:Gpush` `:Gfetch` run in background. See:

- [Replace old ':make' command with asyncrun](https://github.com/skywind3000/asyncrun.vim/wiki/Replace-old-make-command-with-AsyncRun)

- [Cooperate with vim-fugitive](https://github.com/skywind3000/asyncrun.vim/wiki/Cooperate-with-vim-fugitive)

**Comment by mcepl** [comment]
Thanks a lot!

**Comment by skywind3000** [comment]
My pleasure, this is brilliant idea !
