### ISSUE TITLE
运行go命令时参数raw的问题

### ISSUE THREAD

**Issue by yehuohan** [skywind3000/asyncrun.vim#80]
直接运行 :AsyncRun go run test.go
如果test.go没有语法错误，则不会显示输出结果，加raw=1会显示。
如果test.go有语法错错误，raw=1或0均会显示错误信息，但是raw=1的，就不能跳转到错误的地方了。

这个问题能可以解决吗？

**Comment by skywind3000** [comment]
你自己的插件改了 errorformat，自己看，
https://github.com/skywind3000/asyncrun.vim/issues/30
https://github.com/skywind3000/asyncrun.vim/issues/55

请你了解一下 vim 的 errorformat 机制：`:h errorformat`

**Comment by yehuohan** [comment]
ok~~

**Comment by yehuohan** [comment]
冲突的插件是vim-go，楼主可以写一个有冲突的列表～～

**Comment by skywind3000** [comment]
我在faq里写过啊

**Comment by yehuohan** [comment]
呃。。没仔细看。
