### ISSUE TITLE
Can't recognize 'rst2html.py ' when convert rst to html

### ISSUE THREAD

**Issue by winstarst** [skywind3000/asyncrun.vim#89]
:AsyncRun rst2html.py % %.html
:copen

|| [rst2html.py 设备.rst 设备.rst.html]
|| 'ml.py' 不是内部或外部命令，也不是可运行的程序
|| 或批处理文件。
|| [Finished in 1 seconds with code 1]

**Comment by skywind3000** [comment]
路径问题吧。

**Comment by winstarst** [comment]
但是我直接使用 !rst2html.py % %.html 是成功的。

刚才在另外一台机器（win7x64）上测试，发现文件名是英文时正常，中文时失败。
let g:asyncrun_encs = 'gbk'
fenc=utf-8
encoding=utf-8
命令为 :AsyncRun rst2html.py % %.html

文件名为中文时输出如下：
|| [rst2html.py vim80安装备忘.rst vim80安装备忘.rst.html]
|| 'vim80安装备忘.rst' ²»ÊÇÄڲ¿»òÍⲿÃüÁҲ²»ÊǿÉÔËÐеĳÌÐò
|| »òÅú´¦ÀíÎļþ¡£
|| [Finished in 0 seconds with code 1]

文件名为英文时输出如下：
|| [rst2html.py vim80_setup.rst vim80_setup.rst.html]
|| [Finished in 1 seconds]

**Comment by winstarst** [comment]
目前使用 https://github.com/skywind3000/asynctasks.vim 解决了问题，在 task.ini 中添加 command 命令如下：
command:rst=myrst2html.py "$(VIM_FILEPATH)" "$(VIM_PATHNOEXT)".html

**Comment by skywind3000** [comment]
最新版已经解决中文传参数
