### ISSUE TITLE
Every job fails with 'No such file or directory'

### ISSUE THREAD

**Issue by derteta** [skywind3000/asyncrun.vim#9]
Hi,

I'm running the plugin in the latest `vim` (built from the git repository with all the necessary features). Yet, all calls to `AsyncRun` return immediately, and the quickfix list looks like this:

> || ["grep", "-R", "unsigned", "."]                                                                                  
> || executing job failed: No such file or directory
> || [Finished in 0 seconds with code 122]

Not sure what's going on.

**Comment by skywind3000** [comment]
and what OS are you using ?
AsyncRun will execute your command via &shell variable in vim. is it be correctly config ?
what is the output when you use (!) directly ?:

```VimL
:! grep -R unsigned .
```

**Comment by derteta** [comment]
I'm on MacOs 10.8.5 (I know, it's a bit dated).
Running `grep` directly with `!` works fine.

**Comment by skywind3000** [comment]
your asyncrun seems dated too,
can you update to the latest asyncrun and give me some feed back please ?

**Comment by derteta** [comment]
I did, with the same result.
I just tried to run some commands with `job_start` and there seems to be a problem with `vim` itself.
Closing the issue. Thanks for your help.

**Comment by derteta** [comment]
Ok, found it. As soon as I removed the line
`set shell=bash\ -i`
from my `.vimrc`, it worked. I thought this might be interesting for you.

**Comment by skywind3000** [comment]
you should set `shellcmdflag` instead of adjusting `shell`:

```VimL
set shellcmdflag=-ic
```

This is what you want.
