### ISSUE TITLE
Can't print the output one by one？

### ISSUE THREAD

**Issue by Chandlercjy** [skywind3000/asyncrun.vim#93]
Hi，

```{python}
import sys,time
for i in range(100):
    k = i + 1
    str = '>'*(i//2)+' '*((100-k)//2)
    sys.stdout.write('\r'+str+'[%s%%]'%(i+1))
    sys.stdout.flush()
    time.sleep(0.1)
```
比如这个打印进度条的脚本,在Asyncrun无法像在shell里面运行一样动态展示，请问有什么方法让他展示和command line一样吗？动态展示进度条。

command line output：

```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>[100%]
```

AsyncRun:
```
^M                                                 [1%]^M                                                 [2%]^M> …………………………
```
Thank you！

**Comment by skywind3000** [comment]
你为何要用 \r ?? 换行符明名是 \n
把 \r 换成 \n，\r 不识别

**Comment by skywind3000** [comment]
quickfix 窗口本来就是一行行添加的，你可以理解成 emacs 的 eshell，不支持你的 \r，你要 \r 你需要终端。

**Comment by Chandlercjy** [comment]
谢谢~

抱歉可能是我问题表述的不太清楚，其实我是想问如何才能实时的将程序运行的结果显示在quickfix。
比如下面这个脚本：

import time
while 1：
        time.sleep(1)
        print(1)

如果是在终端运行，终端会持续不断打1出来，而如果用Asyncrun运行，则怎么都显示不出来。换句话说Asyncrun是在程序运行结束后，才一次性将结果都输出到quickfix上，而我想能不能像终端一样实时打印，这样便于调试，可以知道程序运行得如何然后便于自己中断。

**Comment by skywind3000** [comment]
那是因为后台进程的输出缓存了，把这行放到你 vimrc 里：

```VimL
let $PYTHONUNBUFFERED=1
```

见 [这里](https://github.com/skywind3000/asyncrun.vim/wiki/FAQ#cant-see-the-realtime-output-when-running-a-python-script)

**Comment by Chandlercjy** [comment]
啊！太感谢了，这样真的方便超多，谢谢！！！

**Comment by skywind3000** [comment]
记得 AsyncRun 运行 python 时加上 -raw 参数：

    :AsyncRun -raw python %

或者更完善点：

    :AsyncRun -cwd=$(VIM_FILEDIR) -raw python "$(VIM_FILENAME)"
