### ISSUE TITLE
关于QUICKFIX中第一行高亮

### ISSUE THREAD

**Issue by CPPCOCOS2DX** [skywind3000/asyncrun.vim#94]
在使用的时候 能不能把QUICKFIX第一行的背景颜色去掉 第一行默认使用的是搜索时候的颜色  (https://img-blog.csdn.net/20180403162717884)

**Comment by skywind3000** [comment]
quickfix 有一个当前选中行，用 cnext, cprev 移动的那个当前行，用于在匹配出来的错误之间上下移动，标注当前的错误，默认选中第一行而已，你可以修改配色，syntax 的名字是 QuickFixLine

**Comment by skywind3000** [comment]
你在 quickfix中上下移动光标，按下回车，当前行就变了，那一行就高亮起来了，这样你查找定位错误的时候还可以低头看一样，现在是在查哪个编译错误，挺有用的东西，我建议你留着。

**Comment by CPPCOCOS2DX** [comment]
谢谢你的解答  不过我在VIM中文手册里面并没有找到QuickFixLine这个关键字  还有要是能自动跟着光标走就好了 而不是还需要按下回车  再者 我一般只是在QUICKFIX中查看输出结果的

**Comment by skywind3000** [comment]
你可以用 highlight 命令关闭它，再，quickfix中跟着光标走的高亮，你可以仅再 quickfix 中自动打开 cursorline

**Comment by CPPCOCOS2DX** [comment]
嗯 是可以用highlight 来关闭 我是这样做的 highlight Search GUIBG=NONE  但是这样的话
在其它窗口搜索的时候 被搜索的内容就不会高亮了 我不知道怎么将这个效果仅限于QUickFix窗口中!!! 因为highlight 没有setlocal这样的设置;我在QuickFix中关闭了cursorline 大概是这样的  setlocal nocursorline

**Comment by skywind3000** [comment]
我晕，我说的是修改 QuickFixLine 这个 syntax 啊，又没叫你修改 Search 的 syntax
这么着不就得了

```VimL
hi def link QuickFixLine Normal
``` 

多看看手册吧，不过显然已经和本插件没关系了。
