### ISSUE TITLE
Latin chars are not displayed correctly

### ISSUE THREAD

**Issue by adrianoviana87** [skywind3000/asyncrun.vim#95]
I'm getting weird chars instead of actual latin character.
See the image.
![image](https://user-images.githubusercontent.com/10091326/38281668-2a05af78-3782-11e8-8c9a-4bd72aae7b56.png)

**Comment by skywind3000** [comment]
have you tried `g:asyncrun_encs` ?? 

You should setup g:asyncrun_encs correctly if your system encoding is different from vim's internal encoding.

**Comment by adrianoviana87** [comment]
My bad. I should have read the documentation first 😞 .
Thank you for your advise. It helped me but I had a hard time to figure out what encoding to use.
I'm on Windows.
After a while I had the idea of running `:!chcp`. I set `g:asyncrun_encs` using the value of the encoding shown by the `chcp` command. That was the right encoding.

Perhaps this should be in the documentation?
